"""This file is generated by scripts/generate-contract-models.py."""
# fmt: off

from __future__ import annotations

import json

from typing import Literal, NotRequired, TypeAlias, TypedDict

JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]

AssignmentOption1 = TypedDict('AssignmentOption1', {
    'definition_kind': 'Literal["implicit"]',
})

AssignmentOption2 = TypedDict('AssignmentOption2', {
    'definition_kind': 'Literal["inherited_assignment"]',
})

AssignmentOption3 = TypedDict('AssignmentOption3', {
    'definition_kind': 'Literal["direct_chain"]',
})

OutputFormatOption1 = TypedDict('OutputFormatOption1', {
    'type': 'NotRequired[Literal["text"]]',
})

OutputFormatOption2 = TypedDict('OutputFormatOption2', {
    'type': 'NotRequired[Literal["json_schema"]]',
})

ModelCallRequestOption1 = TypedDict('ModelCallRequestOption1', {
    'selector': 'NotRequired[AssignmentSelector]',
})

ModelCallRequestOption2 = TypedDict('ModelCallRequestOption2', {
    'selector': 'NotRequired[ExactProviderModelSelector]',
})

MediaJobRequestOption1 = TypedDict('MediaJobRequestOption1', {
    'kind': 'NotRequired[Literal["image", "video"]]',
})

MediaJobRequestOption2 = TypedDict('MediaJobRequestOption2', {
    'kind': 'NotRequired[Literal["audio"]]',
})

ApiName: TypeAlias = str

AssignmentName: TypeAlias = str

OpaqueId: TypeAlias = str

Timestamp: TypeAlias = str

Tag: TypeAlias = str

Tags: TypeAlias = list[Tag]

PageInfo = TypedDict('PageInfo', {
    'has_more': 'bool',
    'next_cursor': 'NotRequired[str]',
})

ErrorCode: TypeAlias = Literal["authentication_required", "permission_denied", "invalid_request", "not_found", "conflict", "assignment_cycle", "provider_unavailable", "upstream_failed", "content_unavailable", "rate_limited", "internal_error"]

ErrorDetails = TypedDict('ErrorDetails', {
    'field': 'NotRequired[str]',
    'reason': 'NotRequired[str]',
})

Error = TypedDict('Error', {
    'code': 'ErrorCode',
    'message': 'str',
    'details': 'NotRequired[ErrorDetails]',
})

ErrorEnvelope = TypedDict('ErrorEnvelope', {
    'error': 'Error',
})

HealthStatus: TypeAlias = Literal["healthy", "degraded", "unavailable"]

HealthSummary = TypedDict('HealthSummary', {
    'status': 'HealthStatus',
    'checked_at': 'Timestamp',
})

WorkspaceCreate = TypedDict('WorkspaceCreate', {
    'api_name': 'ApiName',
    'display_name': 'str',
})

Workspace = TypedDict('Workspace', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'created_at': 'Timestamp',
})

WorkspacePage = TypedDict('WorkspacePage', {
    'items': 'list[Workspace]',
    'page': 'PageInfo',
})

ReasoningLevel: TypeAlias = Literal["none", "low", "medium", "high"]

ProviderModelCandidate = TypedDict('ProviderModelCandidate', {
    'provider_model_api_name': 'ApiName',
})

AssignmentChain: TypeAlias = list[ProviderModelCandidate]

EffectiveAssignmentChain: TypeAlias = list[ProviderModelCandidate]

ObservedRequirement: TypeAlias = Literal["text_input", "image_input", "text_output", "structured_json_output", "tool_calling", "streaming", "reasoning", "embedding_output", "image_output", "video_output", "audio_output"]

AssignmentDefinitionKind: TypeAlias = Literal["implicit", "inherited_assignment", "direct_chain"]

AssignmentWrite = TypedDict('AssignmentWrite', {
    'display_name': 'NotRequired[str]',
    'inherits_assignment_api_name': 'NotRequired[AssignmentName]',
    'direct_chain': 'NotRequired[AssignmentChain]',
    'reasoning_level': 'NotRequired[ReasoningLevel]',
})

Assignment = TypedDict('Assignment', {
    'api_name': 'AssignmentName',
    'display_name': 'str',
    'definition_kind': 'AssignmentDefinitionKind',
    'defined_by_service_api_name': 'NotRequired[ApiName]',
    'inherits_assignment_api_name': 'NotRequired[AssignmentName]',
    'direct_chain': 'NotRequired[AssignmentChain]',
    'effective_chain': 'EffectiveAssignmentChain',
    'reasoning_level': 'NotRequired[ReasoningLevel]',
    'observed_requirements': 'list[ObservedRequirement]',
    'last_used_at': 'NotRequired[Timestamp]',
    'created_at': 'NotRequired[Timestamp]',
})

AssignmentPage = TypedDict('AssignmentPage', {
    'items': 'list[Assignment]',
    'page': 'PageInfo',
})

AssignmentSelector = TypedDict('AssignmentSelector', {
    'assignment_api_name': 'AssignmentName',
})

ExactProviderModelSelector = TypedDict('ExactProviderModelSelector', {
    'provider_model_api_name': 'ApiName',
})

ModelSelector: TypeAlias = AssignmentSelector | ExactProviderModelSelector

TextInputPart = TypedDict('TextInputPart', {
    'type': 'Literal["text"]',
    'text': 'str',
})

ImageInputPart = TypedDict('ImageInputPart', {
    'type': 'Literal["image"]',
    'media_type': 'Literal["image/jpeg", "image/png", "image/webp"]',
    'data_base64': 'str',
})

ToolResultPart = TypedDict('ToolResultPart', {
    'type': 'Literal["tool_result"]',
    'tool_call_id': 'OpaqueId',
    'result_json': 'str',
})

UserContentPart: TypeAlias = TextInputPart | ImageInputPart | ToolResultPart

TextOutputPart = TypedDict('TextOutputPart', {
    'type': 'Literal["text"]',
    'text': 'str',
})

ToolCallPart = TypedDict('ToolCallPart', {
    'type': 'Literal["tool_call"]',
    'id': 'OpaqueId',
    'name': 'str',
    'arguments_json': 'str',
})

AssistantContentPart: TypeAlias = TextOutputPart | ToolCallPart

SystemMessage = TypedDict('SystemMessage', {
    'role': 'Literal["system"]',
    'content': 'str',
})

UserMessage = TypedDict('UserMessage', {
    'role': 'Literal["user"]',
    'content': 'list[UserContentPart]',
})

AssistantMessage = TypedDict('AssistantMessage', {
    'role': 'Literal["assistant"]',
    'content': 'list[AssistantContentPart]',
})

ModelMessage: TypeAlias = SystemMessage | UserMessage | AssistantMessage

ToolDefinition = TypedDict('ToolDefinition', {
    'name': 'str',
    'description': 'str',
    'input_schema_json': 'str',
})

OutputFormat = TypedDict('OutputFormat', {
    'type': 'Literal["text", "json_schema"]',
    'schema_json': 'NotRequired[str]',
})

ModelCallRequest = TypedDict('ModelCallRequest', {
    'workspace_api_name': 'ApiName',
    'selector': 'ModelSelector',
    'excluded_provider_model_api_names': 'NotRequired[list[ApiName]]',
    'messages': 'list[ModelMessage]',
    'tools': 'NotRequired[list[ToolDefinition]]',
    'output_format': 'NotRequired[OutputFormat]',
    'output_limit': 'NotRequired[int]',
    'temperature': 'NotRequired[float]',
    'tags': 'NotRequired[Tags]',
})

UsageUnit: TypeAlias = Literal["input_token", "output_token", "cached_input_token", "image", "video_second", "audio_second", "request", "provider_unit"]

UsageItem = TypedDict('UsageItem', {
    'unit': 'UsageUnit',
    'quantity': 'str',
})

Usage = TypedDict('Usage', {
    'units': 'list[UsageItem]',
    'cost': 'str',
    'currency': 'str',
})

StandardModelCallResult = TypedDict('StandardModelCallResult', {
    'output_type': 'Literal["standard"]',
    'provider_model_api_name': 'ApiName',
    'content': 'list[AssistantContentPart]',
    'usage': 'Usage',
})

StructuredModelCallResult = TypedDict('StructuredModelCallResult', {
    'output_type': 'Literal["structured_json"]',
    'provider_model_api_name': 'ApiName',
    'structured_output_json': 'str',
    'usage': 'Usage',
})

ModelCallResult: TypeAlias = StandardModelCallResult | StructuredModelCallResult

StreamStart = TypedDict('StreamStart', {
    'provider_model_api_name': 'ApiName',
})

StreamTextDelta = TypedDict('StreamTextDelta', {
    'delta': 'str',
})

StreamToolCall = TypedDict('StreamToolCall', {
    'tool_call': 'ToolCallPart',
})

StreamCompleted = TypedDict('StreamCompleted', {
    'provider_model_api_name': 'ApiName',
    'usage': 'Usage',
})

EmbeddingRequest = TypedDict('EmbeddingRequest', {
    'workspace_api_name': 'ApiName',
    'selector': 'ModelSelector',
    'inputs': 'list[str]',
    'tags': 'NotRequired[Tags]',
})

EmbeddingVector = TypedDict('EmbeddingVector', {
    'index': 'int',
    'values': 'list[float]',
})

EmbeddingResult = TypedDict('EmbeddingResult', {
    'provider_model_api_name': 'ApiName',
    'embeddings': 'list[EmbeddingVector]',
    'usage': 'Usage',
})

MediaKind: TypeAlias = Literal["image", "video", "audio"]

MediaJobState: TypeAlias = Literal["pending", "running", "succeeded", "failed"]

MediaJobRequest = TypedDict('MediaJobRequest', {
    'workspace_api_name': 'ApiName',
    'selector': 'ModelSelector',
    'kind': 'MediaKind',
    'prompt': 'str',
    'input_images': 'NotRequired[list[ImageInputPart]]',
    'tags': 'NotRequired[Tags]',
})

MediaContent = TypedDict('MediaContent', {
    'media_type': 'str',
    'size_bytes': 'int',
})

MediaJob = TypedDict('MediaJob', {
    'id': 'OpaqueId',
    'workspace_api_name': 'ApiName',
    'provider_model_api_name': 'ApiName',
    'kind': 'MediaKind',
    'state': 'MediaJobState',
    'content': 'NotRequired[MediaContent]',
    'error': 'NotRequired[Error]',
    'created_at': 'Timestamp',
    'completed_at': 'NotRequired[Timestamp]',
})

Outcome: TypeAlias = Literal["succeeded", "failed"]

StatisticsDimension: TypeAlias = Literal["date", "service", "workspace", "assignment", "provider_model", "outcome", "tag"]

StatisticsBucket = TypedDict('StatisticsBucket', {
    'dimensions': 'list[str]',
    'calls': 'int',
    'attempts': 'int',
    'units': 'list[UsageItem]',
    'cost': 'str',
    'currency': 'str',
})

StatisticsResult = TypedDict('StatisticsResult', {
    'from': 'Timestamp',
    'to': 'Timestamp',
    'group_by': 'list[StatisticsDimension]',
    'buckets': 'list[StatisticsBucket]',
})

AdministratorSessionStart = TypedDict('AdministratorSessionStart', {
    'return_to': 'str',
})

AdministratorSessionRedirect = TypedDict('AdministratorSessionRedirect', {
    'authorization_url': 'str',
})

AdministratorSession = TypedDict('AdministratorSession', {
    'subject': 'str',
    'display_name': 'str',
    'expires_at': 'Timestamp',
    'csrf_token': 'str',
})

ServiceCreate = TypedDict('ServiceCreate', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'parent_service_api_name': 'NotRequired[ApiName]',
})

ServiceUpdate = TypedDict('ServiceUpdate', {
    'display_name': 'str',
    'parent_service_api_name': 'NotRequired[ApiName]',
})

Service = TypedDict('Service', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'parent_service_api_name': 'NotRequired[ApiName]',
    'created_at': 'Timestamp',
})

ServicePage = TypedDict('ServicePage', {
    'items': 'list[Service]',
    'page': 'PageInfo',
})

ServiceKeyCreate = TypedDict('ServiceKeyCreate', {
    'name': 'str',
})

ServiceKey = TypedDict('ServiceKey', {
    'id': 'OpaqueId',
    'name': 'str',
    'created_at': 'Timestamp',
    'last_used_at': 'NotRequired[Timestamp]',
})

ServiceKeyCreated = TypedDict('ServiceKeyCreated', {
    'key': 'ServiceKey',
    'secret': 'str',
})

ServiceKeyPage = TypedDict('ServiceKeyPage', {
    'items': 'list[ServiceKey]',
    'page': 'PageInfo',
})

ProviderAdapter: TypeAlias = Literal["openai", "openai_compatible", "openrouter", "custom", "wavespeed", "ollama", "local_embeddings", "fake"]

ProviderWrite = TypedDict('ProviderWrite', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'adapter': 'ProviderAdapter',
    'endpoint': 'NotRequired[str]',
    'credential_api_name': 'NotRequired[ApiName]',
    'enabled': 'bool',
})

Provider = TypedDict('Provider', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'adapter': 'ProviderAdapter',
    'endpoint': 'NotRequired[str]',
    'credential_api_name': 'NotRequired[ApiName]',
    'enabled': 'bool',
    'created_at': 'Timestamp',
})

ProviderPage = TypedDict('ProviderPage', {
    'items': 'list[Provider]',
    'page': 'PageInfo',
})

InputModality: TypeAlias = Literal["text", "image"]

OutputModality: TypeAlias = Literal["text", "structured_json", "embedding", "image", "video", "audio"]

ModelCapability: TypeAlias = Literal["tool_calling", "streaming", "reasoning"]

ModelConstraints = TypedDict('ModelConstraints', {
    'embedding_dimensions': 'NotRequired[list[int]]',
    'max_input_images': 'NotRequired[int]',
    'max_input_image_bytes': 'NotRequired[int]',
    'max_output_duration_seconds': 'NotRequired[int]',
})

ReasoningMapping = TypedDict('ReasoningMapping', {
    'level': 'ReasoningLevel',
    'provider_value': 'str',
})

ModelWrite = TypedDict('ModelWrite', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'input_modalities': 'list[InputModality]',
    'output_modalities': 'list[OutputModality]',
    'capabilities': 'list[ModelCapability]',
    'constraints': 'NotRequired[ModelConstraints]',
    'price_source': 'NotRequired[str]',
    'price_lookup_key': 'NotRequired[str]',
    'manual_price': 'NotRequired[Price]',
})

Model = TypedDict('Model', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'input_modalities': 'list[InputModality]',
    'output_modalities': 'list[OutputModality]',
    'capabilities': 'list[ModelCapability]',
    'constraints': 'NotRequired[ModelConstraints]',
    'price_source': 'NotRequired[str]',
    'price_lookup_key': 'NotRequired[str]',
    'current_price': 'NotRequired[Price]',
    'created_at': 'Timestamp',
})

ModelPage = TypedDict('ModelPage', {
    'items': 'list[Model]',
    'page': 'PageInfo',
})

ProviderModelWrite = TypedDict('ProviderModelWrite', {
    'api_name': 'ApiName',
    'provider_api_name': 'ApiName',
    'model_api_name': 'ApiName',
    'provider_model_name': 'str',
    'enabled': 'bool',
    'input_modalities': 'NotRequired[list[InputModality]]',
    'output_modalities': 'NotRequired[list[OutputModality]]',
    'capabilities': 'NotRequired[list[ModelCapability]]',
    'constraints': 'NotRequired[ModelConstraints]',
    'reasoning_mappings': 'NotRequired[list[ReasoningMapping]]',
    'price_source': 'NotRequired[str]',
    'price_lookup_key': 'NotRequired[str]',
    'manual_price': 'NotRequired[Price]',
})

Cooldown = TypedDict('Cooldown', {
    'until': 'Timestamp',
    'reason': 'str',
})

ProviderModel = TypedDict('ProviderModel', {
    'api_name': 'ApiName',
    'provider_api_name': 'ApiName',
    'model_api_name': 'ApiName',
    'provider_model_name': 'str',
    'enabled': 'bool',
    'input_modalities': 'list[InputModality]',
    'output_modalities': 'list[OutputModality]',
    'capabilities': 'list[ModelCapability]',
    'constraints': 'NotRequired[ModelConstraints]',
    'reasoning_mappings': 'list[ReasoningMapping]',
    'price_source': 'NotRequired[str]',
    'price_lookup_key': 'NotRequired[str]',
    'effective_price': 'Price',
    'cooldown': 'NotRequired[Cooldown]',
    'created_at': 'Timestamp',
})

ProviderModelPage = TypedDict('ProviderModelPage', {
    'items': 'list[ProviderModel]',
    'page': 'PageInfo',
})

AvailableProviderModel = TypedDict('AvailableProviderModel', {
    'api_name': 'ApiName',
    'display_name': 'str',
    'input_modalities': 'list[InputModality]',
    'output_modalities': 'list[OutputModality]',
    'capabilities': 'list[ModelCapability]',
    'constraints': 'NotRequired[ModelConstraints]',
    'effective_price': 'Price',
})

AvailableProviderModelPage = TypedDict('AvailableProviderModelPage', {
    'items': 'list[AvailableProviderModel]',
    'page': 'PageInfo',
})

CredentialWrite = TypedDict('CredentialWrite', {
    'api_name': 'ApiName',
    'secret': 'str',
})

Credential = TypedDict('Credential', {
    'api_name': 'ApiName',
    'created_at': 'Timestamp',
    'updated_at': 'Timestamp',
})

CredentialPage = TypedDict('CredentialPage', {
    'items': 'list[Credential]',
    'page': 'PageInfo',
})

Price = TypedDict('Price', {
    'currency': 'str',
    'unit_prices': 'list[UnitPrice]',
    'source': 'NotRequired[str]',
    'synchronized_at': 'NotRequired[Timestamp]',
})

UnitPrice = TypedDict('UnitPrice', {
    'unit': 'UsageUnit',
    'amount': 'str',
})

PriceSyncRequest = TypedDict('PriceSyncRequest', {
    'provider_model_api_names': 'NotRequired[list[ApiName]]',
})

PriceSyncItem = TypedDict('PriceSyncItem', {
    'provider_model_api_name': 'ApiName',
    'outcome': 'Literal["updated", "unchanged", "missing", "failed"]',
    'price': 'NotRequired[Price]',
    'message': 'NotRequired[str]',
})

PriceSyncResult = TypedDict('PriceSyncResult', {
    'attempted_at': 'Timestamp',
    'items': 'list[PriceSyncItem]',
})

ModelImportPreviewRequest = TypedDict('ModelImportPreviewRequest', {
    'provider_api_name': 'ApiName',
})

ModelImportCandidate = TypedDict('ModelImportCandidate', {
    'catalog_key': 'str',
    'display_name': 'str',
    'provider_model_name': 'str',
    'input_modalities': 'list[InputModality]',
    'output_modalities': 'list[OutputModality]',
    'capabilities': 'list[ModelCapability]',
    'constraints': 'NotRequired[ModelConstraints]',
})

ModelImportPreview = TypedDict('ModelImportPreview', {
    'provider_api_name': 'ApiName',
    'candidates': 'list[ModelImportCandidate]',
})

ModelImportSelection = TypedDict('ModelImportSelection', {
    'catalog_key': 'str',
    'model_api_name': 'ApiName',
    'provider_model_api_name': 'ApiName',
})

ModelImportRequest = TypedDict('ModelImportRequest', {
    'provider_api_name': 'ApiName',
    'selections': 'list[ModelImportSelection]',
})

ModelImportResult = TypedDict('ModelImportResult', {
    'models': 'list[Model]',
    'provider_models': 'list[ProviderModel]',
})

RequestLogSummary = TypedDict('RequestLogSummary', {
    'id': 'OpaqueId',
    'service_api_name': 'ApiName',
    'workspace_api_name': 'ApiName',
    'assignment_api_name': 'NotRequired[AssignmentName]',
    'provider_model_api_name': 'NotRequired[ApiName]',
    'kind': 'Literal["model", "embedding", "media"]',
    'outcome': 'Outcome',
    'tags': 'NotRequired[Tags]',
    'started_at': 'Timestamp',
})

RequestLog = TypedDict('RequestLog', {
    'summary': 'RequestLogSummary',
    'request_json': 'str',
    'response_json': 'NotRequired[str]',
    'attempts': 'list[RequestAttempt]',
    'media': 'NotRequired[list[LogMedia]]',
})

RequestAttempt = TypedDict('RequestAttempt', {
    'provider_model_api_name': 'ApiName',
    'outcome': 'Outcome',
    'started_at': 'Timestamp',
    'completed_at': 'NotRequired[Timestamp]',
    'usage': 'Usage',
    'applied_prices': 'Price',
    'error': 'NotRequired[Error]',
})

LogMedia = TypedDict('LogMedia', {
    'id': 'OpaqueId',
    'media_type': 'str',
    'role': 'Literal["input", "output"]',
    'size_bytes': 'int',
})

RequestLogPage = TypedDict('RequestLogPage', {
    'items': 'list[RequestLogSummary]',
    'page': 'PageInfo',
})

ActivityEvent = TypedDict('ActivityEvent', {
    'id': 'OpaqueId',
    'actor_subject': 'str',
    'action': 'str',
    'resource_type': 'str',
    'resource_api_name': 'NotRequired[ApiName]',
    'result': 'Literal["succeeded", "failed"]',
    'occurred_at': 'Timestamp',
})

ActivityPage = TypedDict('ActivityPage', {
    'items': 'list[ActivityEvent]',
    'page': 'PageInfo',
})

LogRetentionSettings = TypedDict('LogRetentionSettings', {
    'duration_days': 'int',
})

HealthComponent = TypedDict('HealthComponent', {
    'name': 'str',
    'status': 'HealthStatus',
    'message': 'NotRequired[str]',
})

AdministratorHealth = TypedDict('AdministratorHealth', {
    'status': 'HealthStatus',
    'checked_at': 'Timestamp',
    'components': 'list[HealthComponent]',
})

CONTRACT_SCHEMAS: dict[str, JsonValue] = json.loads(r"""
{
  "ActivityEvent": {
    "additionalProperties": false,
    "properties": {
      "action": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "actor_subject": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "occurred_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "resource_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "resource_type": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "result": {
        "enum": [
          "succeeded",
          "failed"
        ],
        "type": "string"
      }
    },
    "required": [
      "id",
      "actor_subject",
      "action",
      "resource_type",
      "result",
      "occurred_at"
    ],
    "type": "object"
  },
  "ActivityPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/ActivityEvent"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "AdministratorHealth": {
    "additionalProperties": false,
    "properties": {
      "checked_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "components": {
        "items": {
          "$ref": "#/components/schemas/HealthComponent"
        },
        "type": "array"
      },
      "status": {
        "$ref": "#/components/schemas/HealthStatus"
      }
    },
    "required": [
      "status",
      "checked_at",
      "components"
    ],
    "type": "object"
  },
  "AdministratorSession": {
    "additionalProperties": false,
    "properties": {
      "csrf_token": {
        "maxLength": 500,
        "minLength": 16,
        "type": "string"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "expires_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "subject": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "subject",
      "display_name",
      "expires_at",
      "csrf_token"
    ],
    "type": "object"
  },
  "AdministratorSessionRedirect": {
    "additionalProperties": false,
    "properties": {
      "authorization_url": {
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "authorization_url"
    ],
    "type": "object"
  },
  "AdministratorSessionStart": {
    "additionalProperties": false,
    "properties": {
      "return_to": {
        "maxLength": 1000,
        "minLength": 1,
        "pattern": "^/(?:[A-Za-z0-9_?&=.-][A-Za-z0-9/_?&=.-]*)?$",
        "type": "string"
      }
    },
    "required": [
      "return_to"
    ],
    "type": "object"
  },
  "ApiName": {
    "maxLength": 63,
    "minLength": 1,
    "pattern": "^[a-z](?:[a-z0-9-]{0,61}[a-z0-9])?$",
    "type": "string"
  },
  "Assignment": {
    "additionalProperties": false,
    "oneOf": [
      {
        "not": {
          "anyOf": [
            {
              "required": [
                "inherits_assignment_api_name"
              ]
            },
            {
              "required": [
                "direct_chain"
              ]
            }
          ]
        },
        "properties": {
          "definition_kind": {
            "const": "implicit"
          }
        },
        "required": [
          "definition_kind"
        ]
      },
      {
        "not": {
          "anyOf": [
            {
              "required": [
                "direct_chain"
              ]
            }
          ]
        },
        "properties": {
          "definition_kind": {
            "const": "inherited_assignment"
          }
        },
        "required": [
          "definition_kind",
          "inherits_assignment_api_name"
        ]
      },
      {
        "not": {
          "anyOf": [
            {
              "required": [
                "inherits_assignment_api_name"
              ]
            }
          ]
        },
        "properties": {
          "definition_kind": {
            "const": "direct_chain"
          }
        },
        "required": [
          "definition_kind",
          "direct_chain"
        ]
      }
    ],
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "defined_by_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "definition_kind": {
        "$ref": "#/components/schemas/AssignmentDefinitionKind"
      },
      "direct_chain": {
        "$ref": "#/components/schemas/AssignmentChain"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "effective_chain": {
        "$ref": "#/components/schemas/EffectiveAssignmentChain"
      },
      "inherits_assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "last_used_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "observed_requirements": {
        "items": {
          "$ref": "#/components/schemas/ObservedRequirement"
        },
        "type": "array",
        "uniqueItems": true
      },
      "reasoning_level": {
        "$ref": "#/components/schemas/ReasoningLevel"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "definition_kind",
      "effective_chain",
      "observed_requirements"
    ],
    "type": "object"
  },
  "AssignmentChain": {
    "items": {
      "$ref": "#/components/schemas/ProviderModelCandidate"
    },
    "maxItems": 16,
    "minItems": 1,
    "type": "array",
    "uniqueItems": true
  },
  "AssignmentDefinitionKind": {
    "enum": [
      "implicit",
      "inherited_assignment",
      "direct_chain"
    ],
    "type": "string"
  },
  "AssignmentName": {
    "maxLength": 127,
    "minLength": 1,
    "pattern": "^[a-z0-9][a-z0-9._-]*$",
    "type": "string"
  },
  "AssignmentPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Assignment"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "AssignmentSelector": {
    "additionalProperties": false,
    "properties": {
      "assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      }
    },
    "required": [
      "assignment_api_name"
    ],
    "type": "object"
  },
  "AssignmentWrite": {
    "additionalProperties": false,
    "oneOf": [
      {
        "not": {
          "required": [
            "direct_chain"
          ]
        },
        "required": [
          "inherits_assignment_api_name"
        ]
      },
      {
        "not": {
          "required": [
            "inherits_assignment_api_name"
          ]
        },
        "required": [
          "direct_chain"
        ]
      }
    ],
    "properties": {
      "direct_chain": {
        "$ref": "#/components/schemas/AssignmentChain"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "inherits_assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "reasoning_level": {
        "$ref": "#/components/schemas/ReasoningLevel"
      }
    },
    "type": "object"
  },
  "AssistantContentPart": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/TextOutputPart"
      },
      {
        "$ref": "#/components/schemas/ToolCallPart"
      }
    ]
  },
  "AssistantMessage": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "items": {
          "$ref": "#/components/schemas/AssistantContentPart"
        },
        "minItems": 1,
        "type": "array"
      },
      "role": {
        "const": "assistant"
      }
    },
    "required": [
      "role",
      "content"
    ],
    "type": "object"
  },
  "AvailableProviderModel": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "effective_price": {
        "$ref": "#/components/schemas/Price"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "input_modalities",
      "output_modalities",
      "capabilities",
      "effective_price"
    ],
    "type": "object"
  },
  "AvailableProviderModelPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/AvailableProviderModel"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "Cooldown": {
    "additionalProperties": false,
    "properties": {
      "reason": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "until": {
        "$ref": "#/components/schemas/Timestamp"
      }
    },
    "required": [
      "until",
      "reason"
    ],
    "type": "object"
  },
  "Credential": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "updated_at": {
        "$ref": "#/components/schemas/Timestamp"
      }
    },
    "required": [
      "api_name",
      "created_at",
      "updated_at"
    ],
    "type": "object"
  },
  "CredentialPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Credential"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "CredentialWrite": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "secret": {
        "maxLength": 10000,
        "minLength": 1,
        "type": "string",
        "writeOnly": true
      }
    },
    "required": [
      "api_name",
      "secret"
    ],
    "type": "object"
  },
  "EffectiveAssignmentChain": {
    "items": {
      "$ref": "#/components/schemas/ProviderModelCandidate"
    },
    "maxItems": 16,
    "minItems": 0,
    "type": "array",
    "uniqueItems": true
  },
  "EmbeddingRequest": {
    "additionalProperties": false,
    "properties": {
      "inputs": {
        "items": {
          "maxLength": 32768,
          "minLength": 1,
          "type": "string",
          "x-max-utf8-bytes": 32768
        },
        "maxItems": 32,
        "minItems": 1,
        "type": "array",
        "x-max-total-utf8-bytes": 262144
      },
      "selector": {
        "$ref": "#/components/schemas/ModelSelector"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "workspace_api_name",
      "selector",
      "inputs"
    ],
    "type": "object"
  },
  "EmbeddingResult": {
    "additionalProperties": false,
    "properties": {
      "embeddings": {
        "items": {
          "$ref": "#/components/schemas/EmbeddingVector"
        },
        "type": "array"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "provider_model_api_name",
      "embeddings",
      "usage"
    ],
    "type": "object"
  },
  "EmbeddingVector": {
    "additionalProperties": false,
    "properties": {
      "index": {
        "minimum": 0,
        "type": "integer"
      },
      "values": {
        "items": {
          "type": "number",
          "x-finite": true
        },
        "maxItems": 65536,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "index",
      "values"
    ],
    "type": "object"
  },
  "Error": {
    "additionalProperties": false,
    "properties": {
      "code": {
        "$ref": "#/components/schemas/ErrorCode"
      },
      "details": {
        "$ref": "#/components/schemas/ErrorDetails"
      },
      "message": {
        "maxLength": 1000,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "code",
      "message"
    ],
    "type": "object"
  },
  "ErrorCode": {
    "enum": [
      "authentication_required",
      "permission_denied",
      "invalid_request",
      "not_found",
      "conflict",
      "assignment_cycle",
      "provider_unavailable",
      "upstream_failed",
      "content_unavailable",
      "rate_limited",
      "internal_error"
    ],
    "type": "string"
  },
  "ErrorDetails": {
    "additionalProperties": false,
    "properties": {
      "field": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "reason": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "type": "object"
  },
  "ErrorEnvelope": {
    "additionalProperties": false,
    "properties": {
      "error": {
        "$ref": "#/components/schemas/Error"
      }
    },
    "required": [
      "error"
    ],
    "type": "object"
  },
  "ExactProviderModelSelector": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "HealthComponent": {
    "additionalProperties": false,
    "properties": {
      "message": {
        "maxLength": 500,
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "status": {
        "$ref": "#/components/schemas/HealthStatus"
      }
    },
    "required": [
      "name",
      "status"
    ],
    "type": "object"
  },
  "HealthStatus": {
    "enum": [
      "healthy",
      "degraded",
      "unavailable"
    ],
    "type": "string"
  },
  "HealthSummary": {
    "additionalProperties": false,
    "properties": {
      "checked_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "status": {
        "$ref": "#/components/schemas/HealthStatus"
      }
    },
    "required": [
      "status",
      "checked_at"
    ],
    "type": "object"
  },
  "ImageInputPart": {
    "additionalProperties": false,
    "properties": {
      "data_base64": {
        "format": "byte",
        "maxLength": 27962028,
        "minLength": 1,
        "type": "string",
        "x-max-decoded-bytes": 20971520
      },
      "media_type": {
        "enum": [
          "image/jpeg",
          "image/png",
          "image/webp"
        ],
        "type": "string"
      },
      "type": {
        "const": "image"
      }
    },
    "required": [
      "type",
      "media_type",
      "data_base64"
    ],
    "type": "object"
  },
  "InputModality": {
    "enum": [
      "text",
      "image"
    ],
    "type": "string"
  },
  "LogMedia": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "media_type": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "role": {
        "enum": [
          "input",
          "output"
        ],
        "type": "string"
      },
      "size_bytes": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "id",
      "media_type",
      "role",
      "size_bytes"
    ],
    "type": "object"
  },
  "LogRetentionSettings": {
    "additionalProperties": false,
    "properties": {
      "duration_days": {
        "maximum": 30,
        "minimum": 1,
        "type": "integer"
      }
    },
    "required": [
      "duration_days"
    ],
    "type": "object"
  },
  "MediaContent": {
    "additionalProperties": false,
    "properties": {
      "media_type": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "size_bytes": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "media_type",
      "size_bytes"
    ],
    "type": "object"
  },
  "MediaJob": {
    "additionalProperties": false,
    "properties": {
      "completed_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "content": {
        "$ref": "#/components/schemas/MediaContent"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "error": {
        "$ref": "#/components/schemas/Error"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "kind": {
        "$ref": "#/components/schemas/MediaKind"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "state": {
        "$ref": "#/components/schemas/MediaJobState"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "id",
      "workspace_api_name",
      "provider_model_api_name",
      "kind",
      "state",
      "created_at"
    ],
    "type": "object"
  },
  "MediaJobRequest": {
    "additionalProperties": false,
    "oneOf": [
      {
        "properties": {
          "kind": {
            "enum": [
              "image",
              "video"
            ]
          }
        }
      },
      {
        "not": {
          "required": [
            "input_images"
          ]
        },
        "properties": {
          "kind": {
            "const": "audio"
          }
        }
      }
    ],
    "properties": {
      "input_images": {
        "items": {
          "$ref": "#/components/schemas/ImageInputPart"
        },
        "maxItems": 8,
        "type": "array",
        "x-max-total-decoded-bytes": 52428800
      },
      "kind": {
        "$ref": "#/components/schemas/MediaKind"
      },
      "prompt": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "selector": {
        "$ref": "#/components/schemas/ModelSelector"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "workspace_api_name",
      "selector",
      "kind",
      "prompt"
    ],
    "type": "object"
  },
  "MediaJobState": {
    "enum": [
      "pending",
      "running",
      "succeeded",
      "failed"
    ],
    "type": "string"
  },
  "MediaKind": {
    "enum": [
      "image",
      "video",
      "audio"
    ],
    "type": "string"
  },
  "Model": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "current_price": {
        "$ref": "#/components/schemas/Price"
      },
      "display_name": {
        "type": "string"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      },
      "price_lookup_key": {
        "type": "string"
      },
      "price_source": {
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "input_modalities",
      "output_modalities",
      "capabilities",
      "created_at"
    ],
    "type": "object"
  },
  "ModelCallRequest": {
    "additionalProperties": false,
    "oneOf": [
      {
        "properties": {
          "selector": {
            "$ref": "#/components/schemas/AssignmentSelector"
          }
        }
      },
      {
        "not": {
          "required": [
            "excluded_provider_model_api_names"
          ]
        },
        "properties": {
          "selector": {
            "$ref": "#/components/schemas/ExactProviderModelSelector"
          }
        }
      }
    ],
    "properties": {
      "excluded_provider_model_api_names": {
        "items": {
          "$ref": "#/components/schemas/ApiName"
        },
        "maxItems": 16,
        "type": "array",
        "uniqueItems": true
      },
      "messages": {
        "items": {
          "$ref": "#/components/schemas/ModelMessage"
        },
        "maxItems": 1000,
        "minItems": 1,
        "type": "array"
      },
      "output_format": {
        "$ref": "#/components/schemas/OutputFormat"
      },
      "output_limit": {
        "maximum": 1000000,
        "minimum": 1,
        "type": "integer"
      },
      "selector": {
        "$ref": "#/components/schemas/ModelSelector"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "temperature": {
        "maximum": 2,
        "minimum": 0,
        "type": "number"
      },
      "tools": {
        "items": {
          "$ref": "#/components/schemas/ToolDefinition"
        },
        "maxItems": 128,
        "type": "array"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "workspace_api_name",
      "selector",
      "messages"
    ],
    "type": "object",
    "x-max-image-bytes": 52428800,
    "x-max-json-bytes": 2097152
  },
  "ModelCallResult": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/StandardModelCallResult"
      },
      {
        "$ref": "#/components/schemas/StructuredModelCallResult"
      }
    ]
  },
  "ModelCapability": {
    "enum": [
      "tool_calling",
      "streaming",
      "reasoning"
    ],
    "type": "string"
  },
  "ModelConstraints": {
    "additionalProperties": false,
    "properties": {
      "embedding_dimensions": {
        "items": {
          "maximum": 65536,
          "minimum": 1,
          "type": "integer"
        },
        "maxItems": 64,
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "max_input_image_bytes": {
        "maximum": 20971520,
        "minimum": 1,
        "type": "integer"
      },
      "max_input_images": {
        "maximum": 8,
        "minimum": 0,
        "type": "integer"
      },
      "max_output_duration_seconds": {
        "maximum": 86400,
        "minimum": 1,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "ModelImportCandidate": {
    "additionalProperties": false,
    "properties": {
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "catalog_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      },
      "provider_model_name": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "catalog_key",
      "display_name",
      "provider_model_name",
      "input_modalities",
      "output_modalities",
      "capabilities"
    ],
    "type": "object"
  },
  "ModelImportPreview": {
    "additionalProperties": false,
    "properties": {
      "candidates": {
        "items": {
          "$ref": "#/components/schemas/ModelImportCandidate"
        },
        "type": "array"
      },
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_api_name",
      "candidates"
    ],
    "type": "object"
  },
  "ModelImportPreviewRequest": {
    "additionalProperties": false,
    "properties": {
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_api_name"
    ],
    "type": "object"
  },
  "ModelImportRequest": {
    "additionalProperties": false,
    "properties": {
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "selections": {
        "items": {
          "$ref": "#/components/schemas/ModelImportSelection"
        },
        "maxItems": 1000,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "provider_api_name",
      "selections"
    ],
    "type": "object"
  },
  "ModelImportResult": {
    "additionalProperties": false,
    "properties": {
      "models": {
        "items": {
          "$ref": "#/components/schemas/Model"
        },
        "type": "array"
      },
      "provider_models": {
        "items": {
          "$ref": "#/components/schemas/ProviderModel"
        },
        "type": "array"
      }
    },
    "required": [
      "models",
      "provider_models"
    ],
    "type": "object"
  },
  "ModelImportSelection": {
    "additionalProperties": false,
    "properties": {
      "catalog_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "catalog_key",
      "model_api_name",
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "ModelMessage": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/SystemMessage"
      },
      {
        "$ref": "#/components/schemas/UserMessage"
      },
      {
        "$ref": "#/components/schemas/AssistantMessage"
      }
    ]
  },
  "ModelPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Model"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ModelSelector": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/AssignmentSelector"
      },
      {
        "$ref": "#/components/schemas/ExactProviderModelSelector"
      }
    ]
  },
  "ModelWrite": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array",
        "uniqueItems": true
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "manual_price": {
        "$ref": "#/components/schemas/Price"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "price_lookup_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "price_source": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "input_modalities",
      "output_modalities",
      "capabilities"
    ],
    "type": "object"
  },
  "ObservedRequirement": {
    "enum": [
      "text_input",
      "image_input",
      "text_output",
      "structured_json_output",
      "tool_calling",
      "streaming",
      "reasoning",
      "embedding_output",
      "image_output",
      "video_output",
      "audio_output"
    ],
    "type": "string"
  },
  "OpaqueId": {
    "maxLength": 200,
    "minLength": 1,
    "type": "string"
  },
  "Outcome": {
    "enum": [
      "succeeded",
      "failed"
    ],
    "type": "string"
  },
  "OutputFormat": {
    "additionalProperties": false,
    "oneOf": [
      {
        "not": {
          "required": [
            "schema_json"
          ]
        },
        "properties": {
          "type": {
            "const": "text"
          }
        }
      },
      {
        "properties": {
          "type": {
            "const": "json_schema"
          }
        },
        "required": [
          "schema_json"
        ]
      }
    ],
    "properties": {
      "schema_json": {
        "maxLength": 100000,
        "minLength": 2,
        "type": "string"
      },
      "type": {
        "enum": [
          "text",
          "json_schema"
        ],
        "type": "string"
      }
    },
    "required": [
      "type"
    ],
    "type": "object"
  },
  "OutputModality": {
    "enum": [
      "text",
      "structured_json",
      "embedding",
      "image",
      "video",
      "audio"
    ],
    "type": "string"
  },
  "PageInfo": {
    "additionalProperties": false,
    "properties": {
      "has_more": {
        "type": "boolean"
      },
      "next_cursor": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "has_more"
    ],
    "type": "object"
  },
  "Price": {
    "additionalProperties": false,
    "properties": {
      "currency": {
        "pattern": "^[A-Z]{3}$",
        "type": "string"
      },
      "source": {
        "maxLength": 500,
        "type": "string"
      },
      "synchronized_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "unit_prices": {
        "items": {
          "$ref": "#/components/schemas/UnitPrice"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      }
    },
    "required": [
      "currency",
      "unit_prices"
    ],
    "type": "object"
  },
  "PriceSyncItem": {
    "additionalProperties": false,
    "properties": {
      "message": {
        "maxLength": 500,
        "type": "string"
      },
      "outcome": {
        "enum": [
          "updated",
          "unchanged",
          "missing",
          "failed"
        ],
        "type": "string"
      },
      "price": {
        "$ref": "#/components/schemas/Price"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name",
      "outcome"
    ],
    "type": "object"
  },
  "PriceSyncRequest": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_names": {
        "items": {
          "$ref": "#/components/schemas/ApiName"
        },
        "maxItems": 1000,
        "type": "array",
        "uniqueItems": true
      }
    },
    "type": "object"
  },
  "PriceSyncResult": {
    "additionalProperties": false,
    "properties": {
      "attempted_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "items": {
        "items": {
          "$ref": "#/components/schemas/PriceSyncItem"
        },
        "type": "array"
      }
    },
    "required": [
      "attempted_at",
      "items"
    ],
    "type": "object"
  },
  "Provider": {
    "additionalProperties": false,
    "properties": {
      "adapter": {
        "$ref": "#/components/schemas/ProviderAdapter"
      },
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "credential_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "endpoint": {
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "adapter",
      "enabled",
      "created_at"
    ],
    "type": "object"
  },
  "ProviderAdapter": {
    "enum": [
      "openai",
      "openai_compatible",
      "openrouter",
      "custom",
      "wavespeed",
      "ollama",
      "local_embeddings",
      "fake"
    ],
    "type": "string"
  },
  "ProviderModel": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "cooldown": {
        "$ref": "#/components/schemas/Cooldown"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "effective_price": {
        "$ref": "#/components/schemas/Price"
      },
      "enabled": {
        "type": "boolean"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      },
      "price_lookup_key": {
        "type": "string"
      },
      "price_source": {
        "type": "string"
      },
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "provider_model_name": {
        "type": "string"
      },
      "reasoning_mappings": {
        "items": {
          "$ref": "#/components/schemas/ReasoningMapping"
        },
        "type": "array"
      }
    },
    "required": [
      "api_name",
      "provider_api_name",
      "model_api_name",
      "provider_model_name",
      "enabled",
      "input_modalities",
      "output_modalities",
      "capabilities",
      "reasoning_mappings",
      "effective_price",
      "created_at"
    ],
    "type": "object"
  },
  "ProviderModelCandidate": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "ProviderModelPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/ProviderModel"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ProviderModelWrite": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array",
        "uniqueItems": true
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "enabled": {
        "type": "boolean"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "manual_price": {
        "$ref": "#/components/schemas/Price"
      },
      "model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "price_lookup_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "price_source": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "provider_model_name": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "reasoning_mappings": {
        "items": {
          "$ref": "#/components/schemas/ReasoningMapping"
        },
        "maxItems": 4,
        "type": "array"
      }
    },
    "required": [
      "api_name",
      "provider_api_name",
      "model_api_name",
      "provider_model_name",
      "enabled"
    ],
    "type": "object"
  },
  "ProviderPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Provider"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ProviderWrite": {
    "additionalProperties": false,
    "properties": {
      "adapter": {
        "$ref": "#/components/schemas/ProviderAdapter"
      },
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "credential_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "endpoint": {
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "adapter",
      "enabled"
    ],
    "type": "object"
  },
  "ReasoningLevel": {
    "enum": [
      "none",
      "low",
      "medium",
      "high"
    ],
    "type": "string"
  },
  "ReasoningMapping": {
    "additionalProperties": false,
    "properties": {
      "level": {
        "$ref": "#/components/schemas/ReasoningLevel"
      },
      "provider_value": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "level",
      "provider_value"
    ],
    "type": "object"
  },
  "RequestAttempt": {
    "additionalProperties": false,
    "properties": {
      "applied_prices": {
        "$ref": "#/components/schemas/Price"
      },
      "completed_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "error": {
        "$ref": "#/components/schemas/Error"
      },
      "outcome": {
        "$ref": "#/components/schemas/Outcome"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "started_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "provider_model_api_name",
      "outcome",
      "started_at",
      "usage",
      "applied_prices"
    ],
    "type": "object"
  },
  "RequestLog": {
    "additionalProperties": false,
    "properties": {
      "attempts": {
        "items": {
          "$ref": "#/components/schemas/RequestAttempt"
        },
        "type": "array"
      },
      "media": {
        "items": {
          "$ref": "#/components/schemas/LogMedia"
        },
        "type": "array"
      },
      "request_json": {
        "maxLength": 5000000,
        "type": "string"
      },
      "response_json": {
        "maxLength": 5000000,
        "type": "string"
      },
      "summary": {
        "$ref": "#/components/schemas/RequestLogSummary"
      }
    },
    "required": [
      "summary",
      "request_json",
      "attempts"
    ],
    "type": "object"
  },
  "RequestLogPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/RequestLogSummary"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "RequestLogSummary": {
    "additionalProperties": false,
    "properties": {
      "assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "kind": {
        "enum": [
          "model",
          "embedding",
          "media"
        ],
        "type": "string"
      },
      "outcome": {
        "$ref": "#/components/schemas/Outcome"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "started_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "id",
      "service_api_name",
      "workspace_api_name",
      "kind",
      "outcome",
      "started_at"
    ],
    "type": "object"
  },
  "Service": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "parent_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "created_at"
    ],
    "type": "object"
  },
  "ServiceCreate": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "parent_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "api_name",
      "display_name"
    ],
    "type": "object"
  },
  "ServiceKey": {
    "additionalProperties": false,
    "properties": {
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "last_used_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "created_at"
    ],
    "type": "object"
  },
  "ServiceKeyCreate": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "name"
    ],
    "type": "object"
  },
  "ServiceKeyCreated": {
    "additionalProperties": false,
    "properties": {
      "key": {
        "$ref": "#/components/schemas/ServiceKey"
      },
      "secret": {
        "maxLength": 500,
        "minLength": 32,
        "type": "string"
      }
    },
    "required": [
      "key",
      "secret"
    ],
    "type": "object"
  },
  "ServiceKeyPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/ServiceKey"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ServicePage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Service"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ServiceUpdate": {
    "additionalProperties": false,
    "properties": {
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "parent_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "display_name"
    ],
    "type": "object"
  },
  "StandardModelCallResult": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "items": {
          "$ref": "#/components/schemas/AssistantContentPart"
        },
        "minItems": 1,
        "type": "array"
      },
      "output_type": {
        "const": "standard"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "output_type",
      "provider_model_api_name",
      "content",
      "usage"
    ],
    "type": "object"
  },
  "StatisticsBucket": {
    "additionalProperties": false,
    "properties": {
      "attempts": {
        "minimum": 0,
        "type": "integer"
      },
      "calls": {
        "minimum": 0,
        "type": "integer"
      },
      "cost": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "currency": {
        "pattern": "^[A-Z]{3}$",
        "type": "string"
      },
      "dimensions": {
        "items": {
          "maxLength": 200,
          "type": "string"
        },
        "type": "array"
      },
      "units": {
        "items": {
          "$ref": "#/components/schemas/UsageItem"
        },
        "type": "array"
      }
    },
    "required": [
      "dimensions",
      "calls",
      "attempts",
      "units",
      "cost",
      "currency"
    ],
    "type": "object"
  },
  "StatisticsDimension": {
    "enum": [
      "date",
      "service",
      "workspace",
      "assignment",
      "provider_model",
      "outcome",
      "tag"
    ],
    "type": "string"
  },
  "StatisticsResult": {
    "additionalProperties": false,
    "properties": {
      "buckets": {
        "items": {
          "$ref": "#/components/schemas/StatisticsBucket"
        },
        "maxItems": 1000,
        "type": "array"
      },
      "from": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "group_by": {
        "items": {
          "$ref": "#/components/schemas/StatisticsDimension"
        },
        "type": "array"
      },
      "to": {
        "$ref": "#/components/schemas/Timestamp"
      }
    },
    "required": [
      "from",
      "to",
      "group_by",
      "buckets"
    ],
    "type": "object"
  },
  "StreamCompleted": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "provider_model_api_name",
      "usage"
    ],
    "type": "object"
  },
  "StreamStart": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "StreamTextDelta": {
    "additionalProperties": false,
    "properties": {
      "delta": {
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "delta"
    ],
    "type": "object"
  },
  "StreamToolCall": {
    "additionalProperties": false,
    "properties": {
      "tool_call": {
        "$ref": "#/components/schemas/ToolCallPart"
      }
    },
    "required": [
      "tool_call"
    ],
    "type": "object"
  },
  "StructuredModelCallResult": {
    "additionalProperties": false,
    "properties": {
      "output_type": {
        "const": "structured_json"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "structured_output_json": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "output_type",
      "provider_model_api_name",
      "structured_output_json",
      "usage"
    ],
    "type": "object"
  },
  "SystemMessage": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "role": {
        "const": "system"
      }
    },
    "required": [
      "role",
      "content"
    ],
    "type": "object"
  },
  "Tag": {
    "maxLength": 128,
    "minLength": 1,
    "type": "string",
    "x-max-utf8-bytes": 128
  },
  "Tags": {
    "items": {
      "$ref": "#/components/schemas/Tag"
    },
    "maxItems": 32,
    "type": "array",
    "x-max-total-utf8-bytes": 2048
  },
  "TextInputPart": {
    "additionalProperties": false,
    "properties": {
      "text": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "type": {
        "const": "text"
      }
    },
    "required": [
      "type",
      "text"
    ],
    "type": "object"
  },
  "TextOutputPart": {
    "additionalProperties": false,
    "properties": {
      "text": {
        "type": "string"
      },
      "type": {
        "const": "text"
      }
    },
    "required": [
      "type",
      "text"
    ],
    "type": "object"
  },
  "Timestamp": {
    "format": "date-time",
    "type": "string"
  },
  "ToolCallPart": {
    "additionalProperties": false,
    "properties": {
      "arguments_json": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "type": {
        "const": "tool_call"
      }
    },
    "required": [
      "type",
      "id",
      "name",
      "arguments_json"
    ],
    "type": "object"
  },
  "ToolDefinition": {
    "additionalProperties": false,
    "properties": {
      "description": {
        "maxLength": 2000,
        "minLength": 1,
        "type": "string"
      },
      "input_schema_json": {
        "maxLength": 100000,
        "minLength": 2,
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "name",
      "description",
      "input_schema_json"
    ],
    "type": "object"
  },
  "ToolResultPart": {
    "additionalProperties": false,
    "properties": {
      "result_json": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "tool_call_id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "type": {
        "const": "tool_result"
      }
    },
    "required": [
      "type",
      "tool_call_id",
      "result_json"
    ],
    "type": "object"
  },
  "UnitPrice": {
    "additionalProperties": false,
    "properties": {
      "amount": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "unit": {
        "$ref": "#/components/schemas/UsageUnit"
      }
    },
    "required": [
      "unit",
      "amount"
    ],
    "type": "object"
  },
  "Usage": {
    "additionalProperties": false,
    "properties": {
      "cost": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "currency": {
        "pattern": "^[A-Z]{3}$",
        "type": "string"
      },
      "units": {
        "items": {
          "$ref": "#/components/schemas/UsageItem"
        },
        "type": "array"
      }
    },
    "required": [
      "units",
      "cost",
      "currency"
    ],
    "type": "object"
  },
  "UsageItem": {
    "additionalProperties": false,
    "properties": {
      "quantity": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "unit": {
        "$ref": "#/components/schemas/UsageUnit"
      }
    },
    "required": [
      "unit",
      "quantity"
    ],
    "type": "object"
  },
  "UsageUnit": {
    "enum": [
      "input_token",
      "output_token",
      "cached_input_token",
      "image",
      "video_second",
      "audio_second",
      "request",
      "provider_unit"
    ],
    "type": "string"
  },
  "UserContentPart": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/TextInputPart"
      },
      {
        "$ref": "#/components/schemas/ImageInputPart"
      },
      {
        "$ref": "#/components/schemas/ToolResultPart"
      }
    ]
  },
  "UserMessage": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "items": {
          "$ref": "#/components/schemas/UserContentPart"
        },
        "minItems": 1,
        "type": "array"
      },
      "role": {
        "const": "user"
      }
    },
    "required": [
      "role",
      "content"
    ],
    "type": "object"
  },
  "Workspace": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "created_at"
    ],
    "type": "object"
  },
  "WorkspaceCreate": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name"
    ],
    "type": "object"
  },
  "WorkspacePage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Workspace"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  }
}
""")

CONTRACT_SCHEMA_NAMES = frozenset(CONTRACT_SCHEMAS)
