"""Catalog, inheritance, validation, and immutable configuration revisions."""

from llmrouter_backend.accounting.model import (
    PriceComponent,
    SynchronizationState,
    UsageUnit,
)

from .distribution import (
    MAXIMUM_NORMAL_REVISION_AGE,
    AdmissionDistributionSnapshot,
    AuthenticatedNormalRevision,
    AuthenticatedUrgentRevision,
    ConfigurationDistributionError,
    ConfigurationRevisionDistribution,
    CredentialGeneration,
    DistributionErrorCode,
    DistributionSafetyState,
    DistributionScope,
    DistributionStatus,
    NormalConfigurationRevision,
    RevisionAuthenticator,
    UrgentConfigurationRevision,
)
from .errors import ConfigurationError, ConfigurationErrorCode, ValidationIssue
from .model import (
    Assignment,
    AssignmentCandidate,
    CatalogEntry,
    CatalogKind,
    ConfigurationScope,
    ConfigurationState,
    ConfigurationWriteResult,
    DistributionState,
    EffectiveConfiguration,
    EffectiveItem,
    InheritedDisable,
    PriceAuthority,
    PriceAuthorityMode,
    ProviderInstance,
    ProviderModelRoute,
    RegisteredDocument,
    ResourceKind,
    RevisionLayer,
    ScopeConfiguration,
)
from .repository import PostgresConfigurationRepository
from .resolver import resolve_configuration, validate_layers
from .schema import RegisteredSchema, SettingsSchemaRegistry, validate_endpoint

__all__ = [
    "MAXIMUM_NORMAL_REVISION_AGE",
    "AdmissionDistributionSnapshot",
    "Assignment",
    "AssignmentCandidate",
    "AuthenticatedNormalRevision",
    "AuthenticatedUrgentRevision",
    "CatalogEntry",
    "CatalogKind",
    "ConfigurationDistributionError",
    "ConfigurationError",
    "ConfigurationErrorCode",
    "ConfigurationRevisionDistribution",
    "ConfigurationScope",
    "ConfigurationState",
    "ConfigurationWriteResult",
    "CredentialGeneration",
    "DistributionErrorCode",
    "DistributionSafetyState",
    "DistributionScope",
    "DistributionState",
    "DistributionStatus",
    "EffectiveConfiguration",
    "EffectiveItem",
    "InheritedDisable",
    "NormalConfigurationRevision",
    "PostgresConfigurationRepository",
    "PriceAuthority",
    "PriceAuthorityMode",
    "PriceComponent",
    "ProviderInstance",
    "ProviderModelRoute",
    "RegisteredDocument",
    "RegisteredSchema",
    "ResourceKind",
    "RevisionAuthenticator",
    "RevisionLayer",
    "ScopeConfiguration",
    "SettingsSchemaRegistry",
    "SynchronizationState",
    "UrgentConfigurationRevision",
    "UsageUnit",
    "ValidationIssue",
    "resolve_configuration",
    "validate_endpoint",
    "validate_layers",
]
