/* eslint-disable */
/** This file is generated by scripts/generate-contract-models.py. */

export type JsonScalar = string | number | boolean | null;
export type JsonValue = JsonScalar | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue };

export type ApiName = string;

export type AssignmentName = string;

export type OpaqueId = string;

export type Timestamp = string;

export type Tag = string;

export type Tags = ReadonlyArray<Tag>;

export type PageInfo = { readonly has_more: boolean; readonly next_cursor?: string; };

export type ErrorCode = "authentication_required" | "permission_denied" | "invalid_request" | "not_found" | "conflict" | "assignment_cycle" | "provider_unavailable" | "upstream_failed" | "content_unavailable" | "rate_limited" | "internal_error";

export type ErrorDetails = { readonly field?: string; readonly reason?: string; };

export type Error = { readonly code: ErrorCode; readonly message: string; readonly details?: ErrorDetails; };

export type ErrorEnvelope = { readonly error: Error; };

export type HealthStatus = "healthy" | "degraded" | "unavailable";

export type HealthSummary = { readonly status: HealthStatus; readonly checked_at: Timestamp; };

export type WorkspaceCreate = { readonly api_name: ApiName; readonly display_name: string; };

export type Workspace = { readonly api_name: ApiName; readonly display_name: string; readonly created_at: Timestamp; };

export type WorkspacePage = { readonly items: ReadonlyArray<Workspace>; readonly page: PageInfo; };

export type ReasoningLevel = "none" | "low" | "medium" | "high";

export type ProviderModelCandidate = { readonly provider_model_api_name: ApiName; };

export type AssignmentChain = ReadonlyArray<ProviderModelCandidate>;

export type EffectiveAssignmentChain = ReadonlyArray<ProviderModelCandidate>;

export type ObservedRequirement = "text_input" | "image_input" | "text_output" | "structured_json_output" | "tool_calling" | "streaming" | "reasoning" | "embedding_output" | "image_output" | "video_output" | "audio_output";

export type AssignmentDefinitionKind = "implicit" | "inherited_assignment" | "direct_chain";

export type AssignmentWrite = { readonly display_name?: string; readonly inherits_assignment_api_name: AssignmentName; readonly reasoning_level?: ReasoningLevel; } | { readonly display_name?: string; readonly direct_chain: AssignmentChain; readonly reasoning_level?: ReasoningLevel; };

export type Assignment = { readonly api_name: AssignmentName; readonly display_name: string; readonly definition_kind: "implicit"; readonly defined_by_service_api_name?: ApiName; readonly effective_chain: EffectiveAssignmentChain; readonly reasoning_level?: ReasoningLevel; readonly observed_requirements: ReadonlyArray<ObservedRequirement>; readonly last_used_at?: Timestamp; readonly created_at?: Timestamp; } | { readonly api_name: AssignmentName; readonly display_name: string; readonly definition_kind: "inherited_assignment"; readonly defined_by_service_api_name?: ApiName; readonly inherits_assignment_api_name: AssignmentName; readonly effective_chain: EffectiveAssignmentChain; readonly reasoning_level?: ReasoningLevel; readonly observed_requirements: ReadonlyArray<ObservedRequirement>; readonly last_used_at?: Timestamp; readonly created_at?: Timestamp; } | { readonly api_name: AssignmentName; readonly display_name: string; readonly definition_kind: "direct_chain"; readonly defined_by_service_api_name?: ApiName; readonly direct_chain: AssignmentChain; readonly effective_chain: EffectiveAssignmentChain; readonly reasoning_level?: ReasoningLevel; readonly observed_requirements: ReadonlyArray<ObservedRequirement>; readonly last_used_at?: Timestamp; readonly created_at?: Timestamp; };

export type AssignmentPage = { readonly items: ReadonlyArray<Assignment>; readonly page: PageInfo; };

export type AssignmentSelector = { readonly assignment_api_name: AssignmentName; };

export type ExactProviderModelSelector = { readonly provider_model_api_name: ApiName; };

export type ModelSelector = AssignmentSelector | ExactProviderModelSelector;

export type TextInputPart = { readonly type: "text"; readonly text: string; };

export type ImageInputPart = { readonly type: "image"; readonly media_type: "image/jpeg" | "image/png" | "image/webp"; readonly data_base64: string; };

export type ToolResultPart = { readonly type: "tool_result"; readonly tool_call_id: OpaqueId; readonly result_json: string; };

export type UserContentPart = TextInputPart | ImageInputPart | ToolResultPart;

export type TextOutputPart = { readonly type: "text"; readonly text: string; };

export type ToolCallPart = { readonly type: "tool_call"; readonly id: OpaqueId; readonly name: string; readonly arguments_json: string; };

export type AssistantContentPart = TextOutputPart | ToolCallPart;

export type SystemMessage = { readonly role: "system"; readonly content: string; };

export type UserMessage = { readonly role: "user"; readonly content: ReadonlyArray<UserContentPart>; };

export type AssistantMessage = { readonly role: "assistant"; readonly content: ReadonlyArray<AssistantContentPart>; };

export type ModelMessage = SystemMessage | UserMessage | AssistantMessage;

export type ToolDefinition = { readonly name: string; readonly description: string; readonly input_schema_json: string; };

export type OutputFormat = { readonly type: "text"; } | { readonly type: "json_schema"; readonly schema_json: string; };

export type ModelCallRequest = { readonly workspace_api_name: ApiName; readonly selector: ModelSelector; readonly messages: ReadonlyArray<ModelMessage>; readonly tools?: ReadonlyArray<ToolDefinition>; readonly output_format?: OutputFormat; readonly output_limit?: number; readonly temperature?: number; readonly tags?: Tags; };

export type UsageUnit = "input_token" | "output_token" | "cached_input_token" | "image" | "video_second" | "audio_second" | "request" | "provider_unit";

export type UsageItem = { readonly unit: UsageUnit; readonly quantity: string; };

export type Usage = { readonly units: ReadonlyArray<UsageItem>; readonly cost: string; readonly currency: string; };

export type StandardModelCallResult = { readonly output_type: "standard"; readonly provider_model_api_name: ApiName; readonly content: ReadonlyArray<AssistantContentPart>; readonly usage: Usage; };

export type StructuredModelCallResult = { readonly output_type: "structured_json"; readonly provider_model_api_name: ApiName; readonly structured_output_json: string; readonly usage: Usage; };

export type ModelCallResult = StandardModelCallResult | StructuredModelCallResult;

export type StreamStart = { readonly provider_model_api_name: ApiName; };

export type StreamTextDelta = { readonly delta: string; };

export type StreamToolCall = { readonly tool_call: ToolCallPart; };

export type StreamCompleted = { readonly provider_model_api_name: ApiName; readonly usage: Usage; };

export type EmbeddingRequest = { readonly workspace_api_name: ApiName; readonly selector: ModelSelector; readonly inputs: ReadonlyArray<string>; readonly tags?: Tags; };

export type EmbeddingVector = { readonly index: number; readonly values: ReadonlyArray<number>; };

export type EmbeddingResult = { readonly provider_model_api_name: ApiName; readonly embeddings: ReadonlyArray<EmbeddingVector>; readonly usage: Usage; };

export type MediaKind = "image" | "video" | "audio";

export type MediaJobState = "pending" | "running" | "succeeded" | "failed";

export type MediaJobRequest = { readonly workspace_api_name: ApiName; readonly selector: ModelSelector; readonly kind: "image" | "video"; readonly prompt: string; readonly input_images?: ReadonlyArray<ImageInputPart>; readonly tags?: Tags; } | { readonly workspace_api_name: ApiName; readonly selector: ModelSelector; readonly kind: "audio"; readonly prompt: string; readonly tags?: Tags; };

export type MediaContent = { readonly media_type: string; readonly size_bytes: number; };

export type MediaJob = { readonly id: OpaqueId; readonly workspace_api_name: ApiName; readonly provider_model_api_name: ApiName; readonly kind: MediaKind; readonly state: MediaJobState; readonly content?: MediaContent; readonly error?: Error; readonly created_at: Timestamp; readonly completed_at?: Timestamp; };

export type Outcome = "succeeded" | "failed";

export type StatisticsDimension = "date" | "service" | "workspace" | "assignment" | "provider_model" | "outcome" | "tag";

export type StatisticsBucket = { readonly dimensions: ReadonlyArray<string>; readonly calls: number; readonly attempts: number; readonly units: ReadonlyArray<UsageItem>; readonly cost: string; readonly currency: string; };

export type StatisticsResult = { readonly from: Timestamp; readonly to: Timestamp; readonly group_by: ReadonlyArray<StatisticsDimension>; readonly buckets: ReadonlyArray<StatisticsBucket>; };

export type AdministratorSessionStart = { readonly return_to: string; };

export type AdministratorSessionRedirect = { readonly authorization_url: string; };

export type AdministratorSession = { readonly subject: string; readonly display_name: string; readonly expires_at: Timestamp; readonly csrf_token: string; };

export type ServiceCreate = { readonly api_name: ApiName; readonly display_name: string; readonly parent_service_api_name?: ApiName; };

export type ServiceUpdate = { readonly display_name: string; readonly parent_service_api_name?: ApiName; };

export type Service = { readonly api_name: ApiName; readonly display_name: string; readonly parent_service_api_name?: ApiName; readonly created_at: Timestamp; };

export type ServicePage = { readonly items: ReadonlyArray<Service>; readonly page: PageInfo; };

export type ServiceKeyCreate = { readonly name: string; };

export type ServiceKey = { readonly id: OpaqueId; readonly name: string; readonly created_at: Timestamp; readonly last_used_at?: Timestamp; };

export type ServiceKeyCreated = { readonly key: ServiceKey; readonly secret: string; };

export type ServiceKeyPage = { readonly items: ReadonlyArray<ServiceKey>; readonly page: PageInfo; };

export type ProviderAdapter = "openai" | "openai_compatible" | "openrouter" | "custom" | "wavespeed" | "ollama" | "local_embeddings" | "fake";

export type ProviderWrite = { readonly api_name: ApiName; readonly display_name: string; readonly adapter: ProviderAdapter; readonly endpoint?: string; readonly credential_api_name?: ApiName; readonly enabled: boolean; };

export type Provider = { readonly api_name: ApiName; readonly display_name: string; readonly adapter: ProviderAdapter; readonly endpoint?: string; readonly credential_api_name?: ApiName; readonly enabled: boolean; readonly created_at: Timestamp; };

export type ProviderPage = { readonly items: ReadonlyArray<Provider>; readonly page: PageInfo; };

export type InputModality = "text" | "image";

export type OutputModality = "text" | "structured_json" | "embedding" | "image" | "video" | "audio";

export type ModelCapability = "tool_calling" | "streaming" | "reasoning";

export type ModelConstraints = { readonly embedding_dimensions?: ReadonlyArray<number>; readonly max_input_images?: number; readonly max_input_image_bytes?: number; readonly max_output_duration_seconds?: number; };

export type ReasoningMapping = { readonly level: ReasoningLevel; readonly provider_value: string; };

export type ModelWrite = { readonly api_name: ApiName; readonly display_name: string; readonly input_modalities: ReadonlyArray<InputModality>; readonly output_modalities: ReadonlyArray<OutputModality>; readonly capabilities: ReadonlyArray<ModelCapability>; readonly constraints?: ModelConstraints; readonly price_source?: string; readonly price_lookup_key?: string; readonly manual_price?: Price; };

export type Model = { readonly api_name: ApiName; readonly display_name: string; readonly input_modalities: ReadonlyArray<InputModality>; readonly output_modalities: ReadonlyArray<OutputModality>; readonly capabilities: ReadonlyArray<ModelCapability>; readonly constraints?: ModelConstraints; readonly price_source?: string; readonly price_lookup_key?: string; readonly current_price?: Price; readonly created_at: Timestamp; };

export type ModelPage = { readonly items: ReadonlyArray<Model>; readonly page: PageInfo; };

export type ProviderModelWrite = { readonly api_name: ApiName; readonly provider_api_name: ApiName; readonly model_api_name: ApiName; readonly provider_model_name: string; readonly enabled: boolean; readonly input_modalities?: ReadonlyArray<InputModality>; readonly output_modalities?: ReadonlyArray<OutputModality>; readonly capabilities?: ReadonlyArray<ModelCapability>; readonly constraints?: ModelConstraints; readonly reasoning_mappings?: ReadonlyArray<ReasoningMapping>; readonly price_source?: string; readonly price_lookup_key?: string; readonly manual_price?: Price; };

export type Cooldown = { readonly until: Timestamp; readonly reason: string; };

export type ProviderModel = { readonly api_name: ApiName; readonly provider_api_name: ApiName; readonly model_api_name: ApiName; readonly provider_model_name: string; readonly enabled: boolean; readonly input_modalities: ReadonlyArray<InputModality>; readonly output_modalities: ReadonlyArray<OutputModality>; readonly capabilities: ReadonlyArray<ModelCapability>; readonly constraints?: ModelConstraints; readonly reasoning_mappings: ReadonlyArray<ReasoningMapping>; readonly price_source?: string; readonly price_lookup_key?: string; readonly effective_price: Price; readonly cooldown?: Cooldown; readonly created_at: Timestamp; };

export type ProviderModelPage = { readonly items: ReadonlyArray<ProviderModel>; readonly page: PageInfo; };

export type AvailableProviderModel = { readonly api_name: ApiName; readonly display_name: string; readonly input_modalities: ReadonlyArray<InputModality>; readonly output_modalities: ReadonlyArray<OutputModality>; readonly capabilities: ReadonlyArray<ModelCapability>; readonly constraints?: ModelConstraints; readonly effective_price: Price; };

export type AvailableProviderModelPage = { readonly items: ReadonlyArray<AvailableProviderModel>; readonly page: PageInfo; };

export type CredentialWrite = { readonly api_name: ApiName; readonly secret: string; };

export type Credential = { readonly api_name: ApiName; readonly created_at: Timestamp; readonly updated_at: Timestamp; };

export type CredentialPage = { readonly items: ReadonlyArray<Credential>; readonly page: PageInfo; };

export type Price = { readonly currency: string; readonly unit_prices: ReadonlyArray<UnitPrice>; readonly source?: string; readonly synchronized_at?: Timestamp; };

export type UnitPrice = { readonly unit: UsageUnit; readonly amount: string; };

export type PriceSyncRequest = { readonly provider_model_api_names?: ReadonlyArray<ApiName>; };

export type PriceSyncItem = { readonly provider_model_api_name: ApiName; readonly outcome: "updated" | "unchanged" | "missing" | "failed"; readonly price?: Price; readonly message?: string; };

export type PriceSyncResult = { readonly attempted_at: Timestamp; readonly items: ReadonlyArray<PriceSyncItem>; };

export type ModelImportPreviewRequest = { readonly provider_api_name: ApiName; };

export type ModelImportCandidate = { readonly catalog_key: string; readonly display_name: string; readonly provider_model_name: string; readonly input_modalities: ReadonlyArray<InputModality>; readonly output_modalities: ReadonlyArray<OutputModality>; readonly capabilities: ReadonlyArray<ModelCapability>; readonly constraints?: ModelConstraints; };

export type ModelImportPreview = { readonly provider_api_name: ApiName; readonly candidates: ReadonlyArray<ModelImportCandidate>; };

export type ModelImportSelection = { readonly catalog_key: string; readonly model_api_name: ApiName; readonly provider_model_api_name: ApiName; };

export type ModelImportRequest = { readonly provider_api_name: ApiName; readonly selections: ReadonlyArray<ModelImportSelection>; };

export type ModelImportResult = { readonly models: ReadonlyArray<Model>; readonly provider_models: ReadonlyArray<ProviderModel>; };

export type RequestLogSummary = { readonly id: OpaqueId; readonly service_api_name: ApiName; readonly workspace_api_name: ApiName; readonly assignment_api_name?: AssignmentName; readonly provider_model_api_name?: ApiName; readonly kind: "model" | "embedding" | "media"; readonly outcome: Outcome; readonly tags?: Tags; readonly started_at: Timestamp; };

export type RequestLog = { readonly summary: RequestLogSummary; readonly request_json: string; readonly response_json?: string; readonly attempts: ReadonlyArray<RequestAttempt>; readonly media?: ReadonlyArray<LogMedia>; };

export type RequestAttempt = { readonly provider_model_api_name: ApiName; readonly outcome: Outcome; readonly started_at: Timestamp; readonly completed_at?: Timestamp; readonly usage: Usage; readonly applied_prices: Price; readonly error?: Error; };

export type LogMedia = { readonly id: OpaqueId; readonly media_type: string; readonly role: "input" | "output"; readonly size_bytes: number; };

export type RequestLogPage = { readonly items: ReadonlyArray<RequestLogSummary>; readonly page: PageInfo; };

export type ActivityEvent = { readonly id: OpaqueId; readonly actor_subject: string; readonly action: string; readonly resource_type: string; readonly resource_api_name?: ApiName; readonly result: "succeeded" | "failed"; readonly occurred_at: Timestamp; };

export type ActivityPage = { readonly items: ReadonlyArray<ActivityEvent>; readonly page: PageInfo; };

export type LogRetentionSettings = { readonly duration_days: number; };

export type HealthComponent = { readonly name: string; readonly status: HealthStatus; readonly message?: string; };

export type AdministratorHealth = { readonly status: HealthStatus; readonly checked_at: Timestamp; readonly components: ReadonlyArray<HealthComponent>; };

export const contractSchemas = {
  "ActivityEvent": {
    "additionalProperties": false,
    "properties": {
      "action": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "actor_subject": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "occurred_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "resource_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "resource_type": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "result": {
        "enum": [
          "succeeded",
          "failed"
        ],
        "type": "string"
      }
    },
    "required": [
      "id",
      "actor_subject",
      "action",
      "resource_type",
      "result",
      "occurred_at"
    ],
    "type": "object"
  },
  "ActivityPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/ActivityEvent"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "AdministratorHealth": {
    "additionalProperties": false,
    "properties": {
      "checked_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "components": {
        "items": {
          "$ref": "#/components/schemas/HealthComponent"
        },
        "type": "array"
      },
      "status": {
        "$ref": "#/components/schemas/HealthStatus"
      }
    },
    "required": [
      "status",
      "checked_at",
      "components"
    ],
    "type": "object"
  },
  "AdministratorSession": {
    "additionalProperties": false,
    "properties": {
      "csrf_token": {
        "maxLength": 500,
        "minLength": 16,
        "type": "string"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "expires_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "subject": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "subject",
      "display_name",
      "expires_at",
      "csrf_token"
    ],
    "type": "object"
  },
  "AdministratorSessionRedirect": {
    "additionalProperties": false,
    "properties": {
      "authorization_url": {
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "authorization_url"
    ],
    "type": "object"
  },
  "AdministratorSessionStart": {
    "additionalProperties": false,
    "properties": {
      "return_to": {
        "maxLength": 1000,
        "minLength": 1,
        "pattern": "^/(?:[A-Za-z0-9_?&=.-][A-Za-z0-9/_?&=.-]*)?$",
        "type": "string"
      }
    },
    "required": [
      "return_to"
    ],
    "type": "object"
  },
  "ApiName": {
    "maxLength": 63,
    "minLength": 1,
    "pattern": "^[a-z](?:[a-z0-9-]{0,61}[a-z0-9])?$",
    "type": "string"
  },
  "Assignment": {
    "additionalProperties": false,
    "oneOf": [
      {
        "not": {
          "anyOf": [
            {
              "required": [
                "inherits_assignment_api_name"
              ]
            },
            {
              "required": [
                "direct_chain"
              ]
            }
          ]
        },
        "properties": {
          "definition_kind": {
            "const": "implicit"
          }
        },
        "required": [
          "definition_kind"
        ]
      },
      {
        "not": {
          "anyOf": [
            {
              "required": [
                "direct_chain"
              ]
            }
          ]
        },
        "properties": {
          "definition_kind": {
            "const": "inherited_assignment"
          }
        },
        "required": [
          "definition_kind",
          "inherits_assignment_api_name"
        ]
      },
      {
        "not": {
          "anyOf": [
            {
              "required": [
                "inherits_assignment_api_name"
              ]
            }
          ]
        },
        "properties": {
          "definition_kind": {
            "const": "direct_chain"
          }
        },
        "required": [
          "definition_kind",
          "direct_chain"
        ]
      }
    ],
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "defined_by_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "definition_kind": {
        "$ref": "#/components/schemas/AssignmentDefinitionKind"
      },
      "direct_chain": {
        "$ref": "#/components/schemas/AssignmentChain"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "effective_chain": {
        "$ref": "#/components/schemas/EffectiveAssignmentChain"
      },
      "inherits_assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "last_used_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "observed_requirements": {
        "items": {
          "$ref": "#/components/schemas/ObservedRequirement"
        },
        "type": "array",
        "uniqueItems": true
      },
      "reasoning_level": {
        "$ref": "#/components/schemas/ReasoningLevel"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "definition_kind",
      "effective_chain",
      "observed_requirements"
    ],
    "type": "object"
  },
  "AssignmentChain": {
    "items": {
      "$ref": "#/components/schemas/ProviderModelCandidate"
    },
    "maxItems": 16,
    "minItems": 1,
    "type": "array",
    "uniqueItems": true
  },
  "AssignmentDefinitionKind": {
    "enum": [
      "implicit",
      "inherited_assignment",
      "direct_chain"
    ],
    "type": "string"
  },
  "AssignmentName": {
    "maxLength": 127,
    "minLength": 1,
    "pattern": "^[a-z0-9][a-z0-9._-]*$",
    "type": "string"
  },
  "AssignmentPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Assignment"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "AssignmentSelector": {
    "additionalProperties": false,
    "properties": {
      "assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      }
    },
    "required": [
      "assignment_api_name"
    ],
    "type": "object"
  },
  "AssignmentWrite": {
    "additionalProperties": false,
    "oneOf": [
      {
        "not": {
          "required": [
            "direct_chain"
          ]
        },
        "required": [
          "inherits_assignment_api_name"
        ]
      },
      {
        "not": {
          "required": [
            "inherits_assignment_api_name"
          ]
        },
        "required": [
          "direct_chain"
        ]
      }
    ],
    "properties": {
      "direct_chain": {
        "$ref": "#/components/schemas/AssignmentChain"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "inherits_assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "reasoning_level": {
        "$ref": "#/components/schemas/ReasoningLevel"
      }
    },
    "type": "object"
  },
  "AssistantContentPart": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/TextOutputPart"
      },
      {
        "$ref": "#/components/schemas/ToolCallPart"
      }
    ]
  },
  "AssistantMessage": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "items": {
          "$ref": "#/components/schemas/AssistantContentPart"
        },
        "minItems": 1,
        "type": "array"
      },
      "role": {
        "const": "assistant"
      }
    },
    "required": [
      "role",
      "content"
    ],
    "type": "object"
  },
  "AvailableProviderModel": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "effective_price": {
        "$ref": "#/components/schemas/Price"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "input_modalities",
      "output_modalities",
      "capabilities",
      "effective_price"
    ],
    "type": "object"
  },
  "AvailableProviderModelPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/AvailableProviderModel"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "Cooldown": {
    "additionalProperties": false,
    "properties": {
      "reason": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "until": {
        "$ref": "#/components/schemas/Timestamp"
      }
    },
    "required": [
      "until",
      "reason"
    ],
    "type": "object"
  },
  "Credential": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "updated_at": {
        "$ref": "#/components/schemas/Timestamp"
      }
    },
    "required": [
      "api_name",
      "created_at",
      "updated_at"
    ],
    "type": "object"
  },
  "CredentialPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Credential"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "CredentialWrite": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "secret": {
        "maxLength": 10000,
        "minLength": 1,
        "type": "string",
        "writeOnly": true
      }
    },
    "required": [
      "api_name",
      "secret"
    ],
    "type": "object"
  },
  "EffectiveAssignmentChain": {
    "items": {
      "$ref": "#/components/schemas/ProviderModelCandidate"
    },
    "maxItems": 16,
    "minItems": 0,
    "type": "array",
    "uniqueItems": true
  },
  "EmbeddingRequest": {
    "additionalProperties": false,
    "properties": {
      "inputs": {
        "items": {
          "maxLength": 32768,
          "minLength": 1,
          "type": "string",
          "x-max-utf8-bytes": 32768
        },
        "maxItems": 32,
        "minItems": 1,
        "type": "array",
        "x-max-total-utf8-bytes": 262144
      },
      "selector": {
        "$ref": "#/components/schemas/ModelSelector"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "workspace_api_name",
      "selector",
      "inputs"
    ],
    "type": "object"
  },
  "EmbeddingResult": {
    "additionalProperties": false,
    "properties": {
      "embeddings": {
        "items": {
          "$ref": "#/components/schemas/EmbeddingVector"
        },
        "type": "array"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "provider_model_api_name",
      "embeddings",
      "usage"
    ],
    "type": "object"
  },
  "EmbeddingVector": {
    "additionalProperties": false,
    "properties": {
      "index": {
        "minimum": 0,
        "type": "integer"
      },
      "values": {
        "items": {
          "type": "number",
          "x-finite": true
        },
        "maxItems": 65536,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "index",
      "values"
    ],
    "type": "object"
  },
  "Error": {
    "additionalProperties": false,
    "properties": {
      "code": {
        "$ref": "#/components/schemas/ErrorCode"
      },
      "details": {
        "$ref": "#/components/schemas/ErrorDetails"
      },
      "message": {
        "maxLength": 1000,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "code",
      "message"
    ],
    "type": "object"
  },
  "ErrorCode": {
    "enum": [
      "authentication_required",
      "permission_denied",
      "invalid_request",
      "not_found",
      "conflict",
      "assignment_cycle",
      "provider_unavailable",
      "upstream_failed",
      "content_unavailable",
      "rate_limited",
      "internal_error"
    ],
    "type": "string"
  },
  "ErrorDetails": {
    "additionalProperties": false,
    "properties": {
      "field": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "reason": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "type": "object"
  },
  "ErrorEnvelope": {
    "additionalProperties": false,
    "properties": {
      "error": {
        "$ref": "#/components/schemas/Error"
      }
    },
    "required": [
      "error"
    ],
    "type": "object"
  },
  "ExactProviderModelSelector": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "HealthComponent": {
    "additionalProperties": false,
    "properties": {
      "message": {
        "maxLength": 500,
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "status": {
        "$ref": "#/components/schemas/HealthStatus"
      }
    },
    "required": [
      "name",
      "status"
    ],
    "type": "object"
  },
  "HealthStatus": {
    "enum": [
      "healthy",
      "degraded",
      "unavailable"
    ],
    "type": "string"
  },
  "HealthSummary": {
    "additionalProperties": false,
    "properties": {
      "checked_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "status": {
        "$ref": "#/components/schemas/HealthStatus"
      }
    },
    "required": [
      "status",
      "checked_at"
    ],
    "type": "object"
  },
  "ImageInputPart": {
    "additionalProperties": false,
    "properties": {
      "data_base64": {
        "format": "byte",
        "maxLength": 27962028,
        "minLength": 1,
        "type": "string",
        "x-max-decoded-bytes": 20971520
      },
      "media_type": {
        "enum": [
          "image/jpeg",
          "image/png",
          "image/webp"
        ],
        "type": "string"
      },
      "type": {
        "const": "image"
      }
    },
    "required": [
      "type",
      "media_type",
      "data_base64"
    ],
    "type": "object"
  },
  "InputModality": {
    "enum": [
      "text",
      "image"
    ],
    "type": "string"
  },
  "LogMedia": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "media_type": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "role": {
        "enum": [
          "input",
          "output"
        ],
        "type": "string"
      },
      "size_bytes": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "id",
      "media_type",
      "role",
      "size_bytes"
    ],
    "type": "object"
  },
  "LogRetentionSettings": {
    "additionalProperties": false,
    "properties": {
      "duration_days": {
        "maximum": 30,
        "minimum": 1,
        "type": "integer"
      }
    },
    "required": [
      "duration_days"
    ],
    "type": "object"
  },
  "MediaContent": {
    "additionalProperties": false,
    "properties": {
      "media_type": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "size_bytes": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "media_type",
      "size_bytes"
    ],
    "type": "object"
  },
  "MediaJob": {
    "additionalProperties": false,
    "properties": {
      "completed_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "content": {
        "$ref": "#/components/schemas/MediaContent"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "error": {
        "$ref": "#/components/schemas/Error"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "kind": {
        "$ref": "#/components/schemas/MediaKind"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "state": {
        "$ref": "#/components/schemas/MediaJobState"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "id",
      "workspace_api_name",
      "provider_model_api_name",
      "kind",
      "state",
      "created_at"
    ],
    "type": "object"
  },
  "MediaJobRequest": {
    "additionalProperties": false,
    "oneOf": [
      {
        "properties": {
          "kind": {
            "enum": [
              "image",
              "video"
            ]
          }
        }
      },
      {
        "not": {
          "required": [
            "input_images"
          ]
        },
        "properties": {
          "kind": {
            "const": "audio"
          }
        }
      }
    ],
    "properties": {
      "input_images": {
        "items": {
          "$ref": "#/components/schemas/ImageInputPart"
        },
        "maxItems": 8,
        "type": "array",
        "x-max-total-decoded-bytes": 52428800
      },
      "kind": {
        "$ref": "#/components/schemas/MediaKind"
      },
      "prompt": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "selector": {
        "$ref": "#/components/schemas/ModelSelector"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "workspace_api_name",
      "selector",
      "kind",
      "prompt"
    ],
    "type": "object"
  },
  "MediaJobState": {
    "enum": [
      "pending",
      "running",
      "succeeded",
      "failed"
    ],
    "type": "string"
  },
  "MediaKind": {
    "enum": [
      "image",
      "video",
      "audio"
    ],
    "type": "string"
  },
  "Model": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "current_price": {
        "$ref": "#/components/schemas/Price"
      },
      "display_name": {
        "type": "string"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      },
      "price_lookup_key": {
        "type": "string"
      },
      "price_source": {
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "input_modalities",
      "output_modalities",
      "capabilities",
      "created_at"
    ],
    "type": "object"
  },
  "ModelCallRequest": {
    "additionalProperties": false,
    "properties": {
      "messages": {
        "items": {
          "$ref": "#/components/schemas/ModelMessage"
        },
        "maxItems": 1000,
        "minItems": 1,
        "type": "array"
      },
      "output_format": {
        "$ref": "#/components/schemas/OutputFormat"
      },
      "output_limit": {
        "maximum": 1000000,
        "minimum": 1,
        "type": "integer"
      },
      "selector": {
        "$ref": "#/components/schemas/ModelSelector"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "temperature": {
        "maximum": 2,
        "minimum": 0,
        "type": "number"
      },
      "tools": {
        "items": {
          "$ref": "#/components/schemas/ToolDefinition"
        },
        "maxItems": 128,
        "type": "array"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "workspace_api_name",
      "selector",
      "messages"
    ],
    "type": "object",
    "x-max-image-bytes": 52428800,
    "x-max-json-bytes": 2097152
  },
  "ModelCallResult": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/StandardModelCallResult"
      },
      {
        "$ref": "#/components/schemas/StructuredModelCallResult"
      }
    ]
  },
  "ModelCapability": {
    "enum": [
      "tool_calling",
      "streaming",
      "reasoning"
    ],
    "type": "string"
  },
  "ModelConstraints": {
    "additionalProperties": false,
    "properties": {
      "embedding_dimensions": {
        "items": {
          "maximum": 65536,
          "minimum": 1,
          "type": "integer"
        },
        "maxItems": 64,
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "max_input_image_bytes": {
        "maximum": 20971520,
        "minimum": 1,
        "type": "integer"
      },
      "max_input_images": {
        "maximum": 8,
        "minimum": 0,
        "type": "integer"
      },
      "max_output_duration_seconds": {
        "maximum": 86400,
        "minimum": 1,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "ModelImportCandidate": {
    "additionalProperties": false,
    "properties": {
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "catalog_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      },
      "provider_model_name": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "catalog_key",
      "display_name",
      "provider_model_name",
      "input_modalities",
      "output_modalities",
      "capabilities"
    ],
    "type": "object"
  },
  "ModelImportPreview": {
    "additionalProperties": false,
    "properties": {
      "candidates": {
        "items": {
          "$ref": "#/components/schemas/ModelImportCandidate"
        },
        "type": "array"
      },
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_api_name",
      "candidates"
    ],
    "type": "object"
  },
  "ModelImportPreviewRequest": {
    "additionalProperties": false,
    "properties": {
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_api_name"
    ],
    "type": "object"
  },
  "ModelImportRequest": {
    "additionalProperties": false,
    "properties": {
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "selections": {
        "items": {
          "$ref": "#/components/schemas/ModelImportSelection"
        },
        "maxItems": 1000,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "provider_api_name",
      "selections"
    ],
    "type": "object"
  },
  "ModelImportResult": {
    "additionalProperties": false,
    "properties": {
      "models": {
        "items": {
          "$ref": "#/components/schemas/Model"
        },
        "type": "array"
      },
      "provider_models": {
        "items": {
          "$ref": "#/components/schemas/ProviderModel"
        },
        "type": "array"
      }
    },
    "required": [
      "models",
      "provider_models"
    ],
    "type": "object"
  },
  "ModelImportSelection": {
    "additionalProperties": false,
    "properties": {
      "catalog_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "catalog_key",
      "model_api_name",
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "ModelMessage": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/SystemMessage"
      },
      {
        "$ref": "#/components/schemas/UserMessage"
      },
      {
        "$ref": "#/components/schemas/AssistantMessage"
      }
    ]
  },
  "ModelPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Model"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ModelSelector": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/AssignmentSelector"
      },
      {
        "$ref": "#/components/schemas/ExactProviderModelSelector"
      }
    ]
  },
  "ModelWrite": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array",
        "uniqueItems": true
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "manual_price": {
        "$ref": "#/components/schemas/Price"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "price_lookup_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "price_source": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "input_modalities",
      "output_modalities",
      "capabilities"
    ],
    "type": "object"
  },
  "ObservedRequirement": {
    "enum": [
      "text_input",
      "image_input",
      "text_output",
      "structured_json_output",
      "tool_calling",
      "streaming",
      "reasoning",
      "embedding_output",
      "image_output",
      "video_output",
      "audio_output"
    ],
    "type": "string"
  },
  "OpaqueId": {
    "maxLength": 200,
    "minLength": 1,
    "type": "string"
  },
  "Outcome": {
    "enum": [
      "succeeded",
      "failed"
    ],
    "type": "string"
  },
  "OutputFormat": {
    "additionalProperties": false,
    "oneOf": [
      {
        "not": {
          "required": [
            "schema_json"
          ]
        },
        "properties": {
          "type": {
            "const": "text"
          }
        }
      },
      {
        "properties": {
          "type": {
            "const": "json_schema"
          }
        },
        "required": [
          "schema_json"
        ]
      }
    ],
    "properties": {
      "schema_json": {
        "maxLength": 100000,
        "minLength": 2,
        "type": "string"
      },
      "type": {
        "enum": [
          "text",
          "json_schema"
        ],
        "type": "string"
      }
    },
    "required": [
      "type"
    ],
    "type": "object"
  },
  "OutputModality": {
    "enum": [
      "text",
      "structured_json",
      "embedding",
      "image",
      "video",
      "audio"
    ],
    "type": "string"
  },
  "PageInfo": {
    "additionalProperties": false,
    "properties": {
      "has_more": {
        "type": "boolean"
      },
      "next_cursor": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "has_more"
    ],
    "type": "object"
  },
  "Price": {
    "additionalProperties": false,
    "properties": {
      "currency": {
        "pattern": "^[A-Z]{3}$",
        "type": "string"
      },
      "source": {
        "maxLength": 500,
        "type": "string"
      },
      "synchronized_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "unit_prices": {
        "items": {
          "$ref": "#/components/schemas/UnitPrice"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      }
    },
    "required": [
      "currency",
      "unit_prices"
    ],
    "type": "object"
  },
  "PriceSyncItem": {
    "additionalProperties": false,
    "properties": {
      "message": {
        "maxLength": 500,
        "type": "string"
      },
      "outcome": {
        "enum": [
          "updated",
          "unchanged",
          "missing",
          "failed"
        ],
        "type": "string"
      },
      "price": {
        "$ref": "#/components/schemas/Price"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name",
      "outcome"
    ],
    "type": "object"
  },
  "PriceSyncRequest": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_names": {
        "items": {
          "$ref": "#/components/schemas/ApiName"
        },
        "maxItems": 1000,
        "type": "array",
        "uniqueItems": true
      }
    },
    "type": "object"
  },
  "PriceSyncResult": {
    "additionalProperties": false,
    "properties": {
      "attempted_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "items": {
        "items": {
          "$ref": "#/components/schemas/PriceSyncItem"
        },
        "type": "array"
      }
    },
    "required": [
      "attempted_at",
      "items"
    ],
    "type": "object"
  },
  "Provider": {
    "additionalProperties": false,
    "properties": {
      "adapter": {
        "$ref": "#/components/schemas/ProviderAdapter"
      },
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "credential_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "endpoint": {
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "adapter",
      "enabled",
      "created_at"
    ],
    "type": "object"
  },
  "ProviderAdapter": {
    "enum": [
      "openai",
      "openai_compatible",
      "openrouter",
      "custom",
      "wavespeed",
      "ollama",
      "local_embeddings",
      "fake"
    ],
    "type": "string"
  },
  "ProviderModel": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array"
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "cooldown": {
        "$ref": "#/components/schemas/Cooldown"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "effective_price": {
        "$ref": "#/components/schemas/Price"
      },
      "enabled": {
        "type": "boolean"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "type": "array"
      },
      "model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "type": "array"
      },
      "price_lookup_key": {
        "type": "string"
      },
      "price_source": {
        "type": "string"
      },
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "provider_model_name": {
        "type": "string"
      },
      "reasoning_mappings": {
        "items": {
          "$ref": "#/components/schemas/ReasoningMapping"
        },
        "type": "array"
      }
    },
    "required": [
      "api_name",
      "provider_api_name",
      "model_api_name",
      "provider_model_name",
      "enabled",
      "input_modalities",
      "output_modalities",
      "capabilities",
      "reasoning_mappings",
      "effective_price",
      "created_at"
    ],
    "type": "object"
  },
  "ProviderModelCandidate": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "ProviderModelPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/ProviderModel"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ProviderModelWrite": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "capabilities": {
        "items": {
          "$ref": "#/components/schemas/ModelCapability"
        },
        "type": "array",
        "uniqueItems": true
      },
      "constraints": {
        "$ref": "#/components/schemas/ModelConstraints"
      },
      "enabled": {
        "type": "boolean"
      },
      "input_modalities": {
        "items": {
          "$ref": "#/components/schemas/InputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "manual_price": {
        "$ref": "#/components/schemas/Price"
      },
      "model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "output_modalities": {
        "items": {
          "$ref": "#/components/schemas/OutputModality"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "price_lookup_key": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "price_source": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "provider_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "provider_model_name": {
        "maxLength": 500,
        "minLength": 1,
        "type": "string"
      },
      "reasoning_mappings": {
        "items": {
          "$ref": "#/components/schemas/ReasoningMapping"
        },
        "maxItems": 4,
        "type": "array"
      }
    },
    "required": [
      "api_name",
      "provider_api_name",
      "model_api_name",
      "provider_model_name",
      "enabled"
    ],
    "type": "object"
  },
  "ProviderPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Provider"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ProviderWrite": {
    "additionalProperties": false,
    "properties": {
      "adapter": {
        "$ref": "#/components/schemas/ProviderAdapter"
      },
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "credential_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "endpoint": {
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "adapter",
      "enabled"
    ],
    "type": "object"
  },
  "ReasoningLevel": {
    "enum": [
      "none",
      "low",
      "medium",
      "high"
    ],
    "type": "string"
  },
  "ReasoningMapping": {
    "additionalProperties": false,
    "properties": {
      "level": {
        "$ref": "#/components/schemas/ReasoningLevel"
      },
      "provider_value": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "level",
      "provider_value"
    ],
    "type": "object"
  },
  "RequestAttempt": {
    "additionalProperties": false,
    "properties": {
      "applied_prices": {
        "$ref": "#/components/schemas/Price"
      },
      "completed_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "error": {
        "$ref": "#/components/schemas/Error"
      },
      "outcome": {
        "$ref": "#/components/schemas/Outcome"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "started_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "provider_model_api_name",
      "outcome",
      "started_at",
      "usage",
      "applied_prices"
    ],
    "type": "object"
  },
  "RequestLog": {
    "additionalProperties": false,
    "properties": {
      "attempts": {
        "items": {
          "$ref": "#/components/schemas/RequestAttempt"
        },
        "type": "array"
      },
      "media": {
        "items": {
          "$ref": "#/components/schemas/LogMedia"
        },
        "type": "array"
      },
      "request_json": {
        "maxLength": 5000000,
        "type": "string"
      },
      "response_json": {
        "maxLength": 5000000,
        "type": "string"
      },
      "summary": {
        "$ref": "#/components/schemas/RequestLogSummary"
      }
    },
    "required": [
      "summary",
      "request_json",
      "attempts"
    ],
    "type": "object"
  },
  "RequestLogPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/RequestLogSummary"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "RequestLogSummary": {
    "additionalProperties": false,
    "properties": {
      "assignment_api_name": {
        "$ref": "#/components/schemas/AssignmentName"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "kind": {
        "enum": [
          "model",
          "embedding",
          "media"
        ],
        "type": "string"
      },
      "outcome": {
        "$ref": "#/components/schemas/Outcome"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "started_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "tags": {
        "$ref": "#/components/schemas/Tags"
      },
      "workspace_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "id",
      "service_api_name",
      "workspace_api_name",
      "kind",
      "outcome",
      "started_at"
    ],
    "type": "object"
  },
  "Service": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "parent_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "created_at"
    ],
    "type": "object"
  },
  "ServiceCreate": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "parent_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "api_name",
      "display_name"
    ],
    "type": "object"
  },
  "ServiceKey": {
    "additionalProperties": false,
    "properties": {
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "last_used_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "created_at"
    ],
    "type": "object"
  },
  "ServiceKeyCreate": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "name"
    ],
    "type": "object"
  },
  "ServiceKeyCreated": {
    "additionalProperties": false,
    "properties": {
      "key": {
        "$ref": "#/components/schemas/ServiceKey"
      },
      "secret": {
        "maxLength": 500,
        "minLength": 32,
        "type": "string"
      }
    },
    "required": [
      "key",
      "secret"
    ],
    "type": "object"
  },
  "ServiceKeyPage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/ServiceKey"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ServicePage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Service"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  },
  "ServiceUpdate": {
    "additionalProperties": false,
    "properties": {
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "parent_service_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "display_name"
    ],
    "type": "object"
  },
  "StandardModelCallResult": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "items": {
          "$ref": "#/components/schemas/AssistantContentPart"
        },
        "minItems": 1,
        "type": "array"
      },
      "output_type": {
        "const": "standard"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "output_type",
      "provider_model_api_name",
      "content",
      "usage"
    ],
    "type": "object"
  },
  "StatisticsBucket": {
    "additionalProperties": false,
    "properties": {
      "attempts": {
        "minimum": 0,
        "type": "integer"
      },
      "calls": {
        "minimum": 0,
        "type": "integer"
      },
      "cost": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "currency": {
        "pattern": "^[A-Z]{3}$",
        "type": "string"
      },
      "dimensions": {
        "items": {
          "maxLength": 200,
          "type": "string"
        },
        "type": "array"
      },
      "units": {
        "items": {
          "$ref": "#/components/schemas/UsageItem"
        },
        "type": "array"
      }
    },
    "required": [
      "dimensions",
      "calls",
      "attempts",
      "units",
      "cost",
      "currency"
    ],
    "type": "object"
  },
  "StatisticsDimension": {
    "enum": [
      "date",
      "service",
      "workspace",
      "assignment",
      "provider_model",
      "outcome",
      "tag"
    ],
    "type": "string"
  },
  "StatisticsResult": {
    "additionalProperties": false,
    "properties": {
      "buckets": {
        "items": {
          "$ref": "#/components/schemas/StatisticsBucket"
        },
        "maxItems": 1000,
        "type": "array"
      },
      "from": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "group_by": {
        "items": {
          "$ref": "#/components/schemas/StatisticsDimension"
        },
        "type": "array"
      },
      "to": {
        "$ref": "#/components/schemas/Timestamp"
      }
    },
    "required": [
      "from",
      "to",
      "group_by",
      "buckets"
    ],
    "type": "object"
  },
  "StreamCompleted": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "provider_model_api_name",
      "usage"
    ],
    "type": "object"
  },
  "StreamStart": {
    "additionalProperties": false,
    "properties": {
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      }
    },
    "required": [
      "provider_model_api_name"
    ],
    "type": "object"
  },
  "StreamTextDelta": {
    "additionalProperties": false,
    "properties": {
      "delta": {
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "delta"
    ],
    "type": "object"
  },
  "StreamToolCall": {
    "additionalProperties": false,
    "properties": {
      "tool_call": {
        "$ref": "#/components/schemas/ToolCallPart"
      }
    },
    "required": [
      "tool_call"
    ],
    "type": "object"
  },
  "StructuredModelCallResult": {
    "additionalProperties": false,
    "properties": {
      "output_type": {
        "const": "structured_json"
      },
      "provider_model_api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "structured_output_json": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "usage": {
        "$ref": "#/components/schemas/Usage"
      }
    },
    "required": [
      "output_type",
      "provider_model_api_name",
      "structured_output_json",
      "usage"
    ],
    "type": "object"
  },
  "SystemMessage": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "role": {
        "const": "system"
      }
    },
    "required": [
      "role",
      "content"
    ],
    "type": "object"
  },
  "Tag": {
    "maxLength": 128,
    "minLength": 1,
    "type": "string",
    "x-max-utf8-bytes": 128
  },
  "Tags": {
    "items": {
      "$ref": "#/components/schemas/Tag"
    },
    "maxItems": 32,
    "type": "array",
    "x-max-total-utf8-bytes": 2048
  },
  "TextInputPart": {
    "additionalProperties": false,
    "properties": {
      "text": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "type": {
        "const": "text"
      }
    },
    "required": [
      "type",
      "text"
    ],
    "type": "object"
  },
  "TextOutputPart": {
    "additionalProperties": false,
    "properties": {
      "text": {
        "type": "string"
      },
      "type": {
        "const": "text"
      }
    },
    "required": [
      "type",
      "text"
    ],
    "type": "object"
  },
  "Timestamp": {
    "format": "date-time",
    "type": "string"
  },
  "ToolCallPart": {
    "additionalProperties": false,
    "properties": {
      "arguments_json": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "type": {
        "const": "tool_call"
      }
    },
    "required": [
      "type",
      "id",
      "name",
      "arguments_json"
    ],
    "type": "object"
  },
  "ToolDefinition": {
    "additionalProperties": false,
    "properties": {
      "description": {
        "maxLength": 2000,
        "minLength": 1,
        "type": "string"
      },
      "input_schema_json": {
        "maxLength": 100000,
        "minLength": 2,
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "name",
      "description",
      "input_schema_json"
    ],
    "type": "object"
  },
  "ToolResultPart": {
    "additionalProperties": false,
    "properties": {
      "result_json": {
        "maxLength": 1000000,
        "minLength": 1,
        "type": "string"
      },
      "tool_call_id": {
        "$ref": "#/components/schemas/OpaqueId"
      },
      "type": {
        "const": "tool_result"
      }
    },
    "required": [
      "type",
      "tool_call_id",
      "result_json"
    ],
    "type": "object"
  },
  "UnitPrice": {
    "additionalProperties": false,
    "properties": {
      "amount": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "unit": {
        "$ref": "#/components/schemas/UsageUnit"
      }
    },
    "required": [
      "unit",
      "amount"
    ],
    "type": "object"
  },
  "Usage": {
    "additionalProperties": false,
    "properties": {
      "cost": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "currency": {
        "pattern": "^[A-Z]{3}$",
        "type": "string"
      },
      "units": {
        "items": {
          "$ref": "#/components/schemas/UsageItem"
        },
        "type": "array"
      }
    },
    "required": [
      "units",
      "cost",
      "currency"
    ],
    "type": "object"
  },
  "UsageItem": {
    "additionalProperties": false,
    "properties": {
      "quantity": {
        "pattern": "^[0-9]+(?:\\.[0-9]+)?$",
        "type": "string"
      },
      "unit": {
        "$ref": "#/components/schemas/UsageUnit"
      }
    },
    "required": [
      "unit",
      "quantity"
    ],
    "type": "object"
  },
  "UsageUnit": {
    "enum": [
      "input_token",
      "output_token",
      "cached_input_token",
      "image",
      "video_second",
      "audio_second",
      "request",
      "provider_unit"
    ],
    "type": "string"
  },
  "UserContentPart": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/TextInputPart"
      },
      {
        "$ref": "#/components/schemas/ImageInputPart"
      },
      {
        "$ref": "#/components/schemas/ToolResultPart"
      }
    ]
  },
  "UserMessage": {
    "additionalProperties": false,
    "properties": {
      "content": {
        "items": {
          "$ref": "#/components/schemas/UserContentPart"
        },
        "minItems": 1,
        "type": "array"
      },
      "role": {
        "const": "user"
      }
    },
    "required": [
      "role",
      "content"
    ],
    "type": "object"
  },
  "Workspace": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "created_at": {
        "$ref": "#/components/schemas/Timestamp"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name",
      "created_at"
    ],
    "type": "object"
  },
  "WorkspaceCreate": {
    "additionalProperties": false,
    "properties": {
      "api_name": {
        "$ref": "#/components/schemas/ApiName"
      },
      "display_name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "api_name",
      "display_name"
    ],
    "type": "object"
  },
  "WorkspacePage": {
    "additionalProperties": false,
    "properties": {
      "items": {
        "items": {
          "$ref": "#/components/schemas/Workspace"
        },
        "type": "array"
      },
      "page": {
        "$ref": "#/components/schemas/PageInfo"
      }
    },
    "required": [
      "items",
      "page"
    ],
    "type": "object"
  }
} as const;

export type ContractSchemaName = keyof typeof contractSchemas;
