# /// script
# requires-python = ">=3.13"
# dependencies = [
#   "ruamel.yaml==0.18.15",
# ]
# ///
"""Generate strict client models and the contract digest manifest."""
# ruff: noqa: ANN401, C901, E501, EM101, PLR0911, PLR0912, TRY003

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML  # type: ignore[import-not-found]

CONTRACT_ARTIFACT_FILES = (
    "docs/api/README.md",
    "docs/api/business-tool-gateway.md",
    "docs/api/cross-service-conformance.md",
    "docs/api/embed-protocol.md",
    "docs/api/embedding-protocol.md",
    "docs/api/errors.md",
    "docs/api/openapi.yaml",
    "docs/api/request-fingerprint.md",
    "docs/api/service-management.md",
    "docs/api/stream-protocol.md",
)
GENERATED_NOTICE = "This file is generated by scripts/generate-contract-models.py."
GENERATOR_VERSION = 1


def load_spec(root: Path) -> dict[str, Any]:
    """Load the accepted OpenAPI source."""
    yaml = YAML(typ="safe")
    value = yaml.load((root / "docs/api/openapi.yaml").read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError("The OpenAPI source must be an object.")
    return value


def literal(value: Any, *, typescript: bool) -> str:
    """Render one string, number, Boolean, or null literal."""
    if value is None:
        return "null" if typescript else "None"
    if isinstance(value, bool):
        if typescript:
            return str(value).lower()
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def python_type(schema: dict[str, Any], inline_names: dict[int, str]) -> str:
    """Render the Python type for one JSON Schema node."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", maxsplit=1)[-1]
    if "const" in schema:
        return f"Literal[{literal(schema['const'], typescript=False)}]"
    if "enum" in schema:
        values = ", ".join(literal(value, typescript=False) for value in schema["enum"])
        return f"Literal[{values}]"
    alternatives = schema.get("oneOf") or schema.get("anyOf")
    if alternatives:
        return " | ".join(python_type(item, inline_names) for item in alternatives)
    if "allOf" in schema:
        refs = [python_type(item, inline_names) for item in schema["allOf"]]
        return refs[0] if len(set(refs)) == 1 else "dict[str, JsonValue]"
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "None"
            if item == "null"
            else python_type({**schema, "type": item}, inline_names)
            for item in schema_type
        )
    if schema_type == "string":
        return "str"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "null":
        return "None"
    if schema_type == "array":
        return f"list[{python_type(schema.get('items', {}), inline_names)}]"
    if schema_type == "object" or "properties" in schema:
        return inline_names.get(id(schema), "dict[str, JsonValue]")
    return "JsonValue"


def typescript_type(schema: dict[str, Any]) -> str:
    """Render the TypeScript type for one JSON Schema node."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", maxsplit=1)[-1]
    if "const" in schema:
        return literal(schema["const"], typescript=True)
    if "enum" in schema:
        return " | ".join(literal(value, typescript=True) for value in schema["enum"])
    alternatives = schema.get("oneOf") or schema.get("anyOf")
    if alternatives and (schema.get("type") == "object" or "properties" in schema):
        return " | ".join(
            typescript_type(merge_object_variant(schema, item)) for item in alternatives
        )
    if alternatives:
        return " | ".join(typescript_type(item) for item in alternatives)
    if "allOf" in schema and not (
        schema.get("type") == "object" or "properties" in schema
    ):
        return " & ".join(typescript_type(item) for item in schema["allOf"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "null" if item == "null" else typescript_type({**schema, "type": item})
            for item in schema_type
        )
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"ReadonlyArray<{typescript_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        fields = [
            f"readonly {name}{'' if name in required else '?'}: {typescript_type(value)};"
            for name, value in properties.items()
        ]
        if schema.get("additionalProperties") not in {None, False}:
            fields.append("readonly [key: string]: JsonValue;")
        return "{ " + " ".join(fields) + " }"
    return "JsonValue"


def merge_object_variant(
    schema: dict[str, Any], variant: dict[str, Any]
) -> dict[str, Any]:
    """Merge one object variant with its common fields."""
    properties = copy.deepcopy(schema.get("properties", {}))
    for name, override in variant.get("properties", {}).items():
        if override:
            properties[name] = copy.deepcopy(override)

    forbidden = set(variant.get("not", {}).get("required", []))
    for denied in variant.get("not", {}).get("anyOf", []):
        forbidden.update(denied.get("required", []))
    for name in forbidden:
        properties.pop(name, None)

    return {
        "type": "object",
        "additionalProperties": schema.get("additionalProperties", False),
        "required": sorted(
            (set(schema.get("required", [])) | set(variant.get("required", [])))
            - forbidden
        ),
        "properties": properties,
    }


def pascal_name(value: str) -> str:
    """Convert one schema path to a stable Python class name."""
    words = re.findall(r"[A-Za-z0-9]+", value)
    return "".join(word[:1].upper() + word[1:] for word in words)


def collect_inline_objects(schemas: dict[str, Any]) -> dict[int, str]:
    """Name each nested object so that variant fields stay explicit."""
    result: dict[int, str] = {}
    used = set(schemas)

    def visit(node: Any, path: str, *, top: bool = False) -> None:
        if isinstance(node, list):
            for index, item in enumerate(node):
                visit(item, f"{path}Option{index + 1}")
            return
        if not isinstance(node, dict):
            return
        if not top and (node.get("type") == "object" or "properties" in node):
            candidate = pascal_name(path)
            base = candidate
            suffix = 2
            while candidate in used:
                candidate = f"{base}{suffix}"
                suffix += 1
            used.add(candidate)
            result[id(node)] = candidate
        for key, child in node.items():
            if key == "properties" and isinstance(child, dict):
                for name, property_schema in child.items():
                    visit(property_schema, f"{path}{pascal_name(name)}")
            elif key == "items":
                visit(child, f"{path}Item")
            elif key in {"oneOf", "anyOf", "allOf"}:
                visit(child, path)

    for name, schema in schemas.items():
        visit(schema, name, top=True)
    return result


def render_python_class(
    name: str, schema: dict[str, Any], inline_names: dict[int, str]
) -> list[str]:
    """Render one generated TypedDict class."""
    fields: list[str] = []
    required = set(schema.get("required", []))
    for property_name, property_schema in schema.get("properties", {}).items():
        rendered = python_type(property_schema, inline_names)
        if property_name not in required:
            rendered = f"NotRequired[{rendered}]"
        fields.append(f"    {property_name!r}: {rendered!r},")
    return [f"{name} = TypedDict({name!r}, {{", *fields, "})", ""]


def render_python(spec: dict[str, Any]) -> str:
    """Render Python contract types and source schemas."""
    schemas = spec["components"]["schemas"]
    inline_names = collect_inline_objects(schemas)
    lines = [
        f'"""{GENERATED_NOTICE}"""',
        "# fmt: off",
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "",
        "from typing import Literal, NotRequired, TypeAlias, TypedDict",
        "",
        "JsonScalar: TypeAlias = str | int | float | bool | None",
        'JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]',
        "",
    ]
    inline_schemas: dict[str, dict[str, Any]] = {}

    def collect(node: Any) -> None:
        if isinstance(node, dict):
            name = inline_names.get(id(node))
            if name is not None:
                inline_schemas[name] = node
            for child in node.values():
                collect(child)
        elif isinstance(node, list):
            for child in node:
                collect(child)

    collect(schemas)
    for name, schema in inline_schemas.items():
        lines.extend(render_python_class(name, schema, inline_names))
    for name, schema in schemas.items():
        if schema.get("type") == "object" and "properties" in schema:
            lines.extend(render_python_class(name, schema, inline_names))
        else:
            lines.extend(
                (f"{name}: TypeAlias = {python_type(schema, inline_names)}", "")
            )
    schema_json = json.dumps(schemas, indent=2, sort_keys=True, ensure_ascii=False)
    lines.extend(
        (
            'CONTRACT_SCHEMAS: dict[str, JsonValue] = json.loads(r"""',
            schema_json,
            '""")',
            "",
            "CONTRACT_SCHEMA_NAMES = frozenset(CONTRACT_SCHEMAS)",
            "",
        )
    )
    return "\n".join(lines)


def render_typescript(spec: dict[str, Any]) -> str:
    """Render TypeScript contract types and source schemas."""
    schemas = spec["components"]["schemas"]
    lines = [
        "/* eslint-disable */",
        f"/** {GENERATED_NOTICE} */",
        "",
        "export type JsonScalar = string | number | boolean | null;",
        "export type JsonValue = JsonScalar | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue };",
        "",
    ]
    for name, schema in schemas.items():
        lines.extend((f"export type {name} = {typescript_type(schema)};", ""))
    schema_json = json.dumps(schemas, indent=2, sort_keys=True, ensure_ascii=False)
    lines.extend(
        (
            f"export const contractSchemas = {schema_json} as const;",
            "",
            "export type ContractSchemaName = keyof typeof contractSchemas;",
            "",
        )
    )
    return "\n".join(lines)


def render_digest_manifest(root: Path, spec: dict[str, Any]) -> str:
    """Render the materialized SHA-256 digest manifest."""
    info = spec["info"]
    manifest = {
        "contract_set": "llmrouter-v1",
        "generator_version": GENERATOR_VERSION,
        "source_sha256": hashlib.sha256(
            (root / "docs/api/openapi.yaml").read_bytes()
        ).hexdigest(),
        "version": info["version"],
        "artifacts": [
            {
                "path": path,
                "sha256": hashlib.sha256((root / path).read_bytes()).hexdigest(),
            }
            for path in CONTRACT_ARTIFACT_FILES
        ],
        "component_schemas": {
            name: hashlib.sha256(
                json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()
            ).hexdigest()
            for name, schema in spec["components"]["schemas"].items()
        },
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def expected_outputs(root: Path) -> dict[Path, str]:
    """Return every generated path and its expected content."""
    spec = load_spec(root)
    typescript = render_typescript(spec)
    return {
        root
        / "packages/python-client/src/llmrouter_client/generated_models.py": render_python(
            spec
        ),
        root / "packages/typescript-server-client/src/generated-models.ts": typescript,
        root / "packages/typescript-browser-client/src/generated-models.ts": typescript,
        root / "docs/api/contract-digests.json": render_digest_manifest(root, spec),
    }


def check_outputs(outputs: dict[Path, str]) -> list[Path]:
    """Return paths that are missing or stale."""
    return [
        path
        for path, expected in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]


def write_outputs(outputs: dict[Path, str]) -> None:
    """Write all generated outputs."""
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def self_test(root: Path) -> None:
    """Prove that the drift check rejects stale generated content."""
    outputs = expected_outputs(root)
    with tempfile.TemporaryDirectory() as temporary_directory:
        stale = Path(temporary_directory) / "generated.py"
        stale.write_text("stale\n", encoding="utf-8")
        if check_outputs({stale: next(iter(outputs.values()))}) != [stale]:
            raise RuntimeError(
                "The generated drift expected-failure test did not fail."
            )
    spec = load_spec(root)
    mutated = copy.deepcopy(spec)
    mutated["components"]["schemas"]["OpaqueId"]["maxLength"] = 201
    if render_python(mutated) == render_python(spec):
        raise RuntimeError(
            "An OpenAPI schema mutation did not change generated output."
        )
    object_union = typescript_type(
        {
            "type": "object",
            "required": ["identity"],
            "properties": {
                "identity": {"type": "string"},
                "state": {"type": "string"},
                "result": {"type": "string"},
            },
            "oneOf": [
                {
                    "required": ["result"],
                    "properties": {"state": {"const": "done"}},
                },
                {
                    "properties": {"state": {"const": "pending"}},
                    "not": {"required": ["result"]},
                },
            ],
        }
    )
    if (
        "readonly identity: string" not in object_union
        or object_union.count("readonly result: string") != 1
    ):
        raise RuntimeError("A TypeScript object union lost common or variant fields.")


def main() -> int:
    """Generate files or check that committed files are current."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    if args.self_test:
        self_test(root)
        print("Contract generation self-test passed.")
        return 0
    outputs = expected_outputs(root)
    if args.check:
        stale = check_outputs(outputs)
        if stale:
            paths = ", ".join(str(path.relative_to(root)) for path in stale)
            print(f"Generated contract drift: {paths}", file=sys.stderr)
            return 1
    else:
        write_outputs(outputs)
    print("Contract model generation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
